import { formatBytes } from "./download";
import { getProfile } from "./profiles/index";
import { SITE_HOST } from "./site";
import type { GeneratedFile } from "./types";

/**
 * What a file *is*, written for something that cannot see the map.
 *
 * The same block is rendered on screen, copied to the clipboard, and written
 * into a package README — built once as structure so those three can never
 * drift apart.
 */
export interface ContextBlock {
  intro: string;
  fields: Array<[string, string]>;
  heading: string;
  problems: string[];
}

export function buildContext(file: GeneratedFile, formatLabel: string): ContextBlock {
  const profile = getProfile(file.stats.profile);
  const fields: Array<[string, string]> = [
    ["File", file.filename],
    ["Format", formatLabel],
    ["Data type", profile.family === "generic" ? profile.label : `${profile.label} — ${profile.blurb}`],
    ["Size", formatBytes(file.bytes)],
    ["Features", file.stats.features.toLocaleString()],
    ["Positions", file.map.total.toLocaleString()],
  ];

  if (file.map.bbox) {
    const [minX, minY, maxX, maxY] = file.map.bbox;
    fields.push(["Bounds", `${minX}, ${minY} to ${maxX}, ${maxY}`]);
  }
  if (file.map.outOfRange || file.map.invalid) {
    fields.push([
      "Off-world",
      `${(file.map.outOfRange + file.map.invalid).toLocaleString()} positions` +
        (file.map.invalid ? ` (${file.map.invalid.toLocaleString()} not a number)` : ""),
    ]);
  }

  return {
    intro: `This is a deliberately broken geospatial test fixture, generated by Null Island (${SITE_HOST}).`,
    fields,
    heading: "Known problems baked into this file:",
    problems: file.notes.length
      ? file.notes
      : ["None. This is a clean, well-formed file, useful as a control case."],
  };
}

export function contextToText(block: ContextBlock): string {
  return [
    block.intro,
    "",
    ...block.fields.map(([label, value]) => `${label}: ${value}`),
    "",
    block.heading,
    ...block.problems.map((p) => `- ${p}`),
  ].join("\n");
}
