/**
 * The gazetteer a generated search term is built from — and asserted against.
 *
 * A list of query strings is not a test fixture. "Devices in Cambridge" is only
 * useful if something beside it says which Cambridge, where it is, and that
 * there are two of them; otherwise you are eyeballing results rather than
 * asserting on them. So every place here carries the answer a geocoder is
 * supposed to return, and the reason it usually doesn't: the other place with
 * the same name, the name the locals use, the name it had until 1995, and the
 * bounding box that is four times bigger than anyone expects.
 *
 * Coordinates are real and centroids are approximate — a city is not a point,
 * and the bbox is the thing you filter on anyway. Nothing in here is invented:
 * an invented ambiguity would fail a geocoder for a reason no user will ever
 * reproduce.
 */

export type PlaceKind = "venue" | "city" | "region" | "country";

export type AliasKind =
  /** What English calls it: Munich, Florence, Lisbon. */
  | "exonym"
  /** What it calls itself: München, Firenze, Lisboa. */
  | "endonym"
  /** NYC, UAE, CDMX. */
  | "abbreviation"
  /** The name it used to have, still typed by half your users. */
  | "former"
  /** Not the real name, but what people say. Holland for the Netherlands. */
  | "colloquial"
  /** An airport or station code standing in for the place. */
  | "code";

export interface Alias {
  name: string;
  kind: AliasKind;
}

export interface Place {
  id: string;
  /** The canonical name, spelled the way a geocoder should return it. */
  name: string;
  kind: PlaceKind;
  lon: number;
  lat: number;
  /** [minLon, minLat, maxLon, maxLat]. A venue still gets one, a block across. */
  bbox: [number, number, number, number];
  /** ISO 3166-1 alpha-2. */
  country: string;
  /** The place this one sits inside — a venue's city, a city's country. */
  within?: string;
  /** Other names for the same place. Every one of these is really used. */
  aliases?: Alias[];
  /**
   * Somewhere else with this name. The reason "Cambridge" is not an answer, and
   * the reason a geocoder that returns one result without saying so is wrong.
   */
  ambiguousWith?: string[];
  /** Rough population, which is how a ranker breaks the tie. */
  population?: number;
  /** Something true about this place that breaks a filter written for it. */
  note?: string;
}

/** A venue sits on a point; the box is roughly the site around it. */
function site(lon: number, lat: number, km = 0.4): [number, number, number, number] {
  const dLat = km / 111;
  const dLon = km / (111 * Math.max(0.1, Math.cos((lat * Math.PI) / 180)));
  return [
    Number((lon - dLon).toFixed(4)),
    Number((lat - dLat).toFixed(4)),
    Number((lon + dLon).toFixed(4)),
    Number((lat + dLat).toFixed(4)),
  ];
}

export const PLACES: Place[] = [
  /* ── Countries ─────────────────────────────────────────────────────────── */
  {
    id: "nz",
    name: "New Zealand",
    kind: "country",
    lon: 174.0,
    lat: -41.0,
    bbox: [166.43, -47.29, 178.55, -34.39],
    country: "NZ",
    aliases: [
      { name: "NZ", kind: "abbreviation" },
      { name: "Aotearoa", kind: "endonym" },
    ],
    population: 5_220_000,
    note: "The box above is the main islands. Include the Chatham Islands and it crosses the antimeridian to about -176, so a naive minLon/maxLon filter for New Zealand either drops the Chathams or selects the entire planet.",
  },
  {
    id: "pt",
    name: "Portugal",
    kind: "country",
    lon: -8.2,
    lat: 39.5,
    bbox: [-9.53, 36.96, -6.19, 42.15],
    country: "PT",
    population: 10_640_000,
    note: "Mainland only. Portugal legally includes the Azores, which reach -31.3° — the real national bbox is more than three times as wide as the one everyone draws.",
  },
  {
    id: "jp",
    name: "Japan",
    kind: "country",
    lon: 138.0,
    lat: 36.5,
    bbox: [122.93, 24.04, 153.99, 45.52],
    country: "JP",
    aliases: [{ name: "日本", kind: "endonym" }, { name: "Nippon", kind: "endonym" }],
    population: 123_900_000,
  },
  {
    id: "gb",
    name: "United Kingdom",
    kind: "country",
    lon: -2.5,
    lat: 54.0,
    bbox: [-8.65, 49.86, 1.77, 60.86],
    country: "GB",
    aliases: [
      { name: "UK", kind: "abbreviation" },
      { name: "Britain", kind: "colloquial" },
      { name: "England", kind: "colloquial" },
      { name: "Great Britain", kind: "colloquial" },
    ],
    population: 68_300_000,
    note: "\"England\" and \"Britain\" are typed for it constantly and neither one means it. England excludes Scotland, Wales and Northern Ireland; Great Britain excludes Northern Ireland. Resolving either to the UK returns devices the user did not ask for.",
  },
  {
    id: "fr",
    name: "France",
    kind: "country",
    lon: 2.5,
    lat: 46.5,
    bbox: [-5.14, 41.33, 9.56, 51.09],
    country: "FR",
    population: 68_400_000,
    note: "Metropolitan France. With the overseas departments — Guadeloupe, Réunion, French Guiana, French Polynesia — France spans about 300° of longitude and both hemispheres. Whichever box you picked, some dataset disagrees.",
  },
  {
    id: "de",
    name: "Germany",
    kind: "country",
    lon: 10.4,
    lat: 51.2,
    bbox: [5.87, 47.27, 15.04, 55.06],
    country: "DE",
    aliases: [{ name: "Deutschland", kind: "endonym" }],
    population: 83_500_000,
  },
  {
    id: "us",
    name: "United States",
    kind: "country",
    lon: -98.5,
    lat: 39.8,
    bbox: [-124.85, 24.4, -66.88, 49.4],
    country: "US",
    aliases: [
      { name: "USA", kind: "abbreviation" },
      { name: "US", kind: "abbreviation" },
      { name: "America", kind: "colloquial" },
    ],
    population: 335_000_000,
    note: "Contiguous states only. Alaska's Aleutians cross the antimeridian to about 172°E, so the true US bbox wraps — and every filter written as minLon < x < maxLon silently excludes them.",
  },
  {
    id: "au",
    name: "Australia",
    kind: "country",
    lon: 134.0,
    lat: -25.0,
    bbox: [112.92, -43.74, 153.64, -10.06],
    country: "AU",
    aliases: [{ name: "Oz", kind: "colloquial" }],
    population: 26_700_000,
  },
  {
    id: "br",
    name: "Brazil",
    kind: "country",
    lon: -51.9,
    lat: -14.2,
    bbox: [-73.99, -33.75, -34.79, 5.27],
    country: "BR",
    aliases: [{ name: "Brasil", kind: "endonym" }],
    population: 213_400_000,
  },
  {
    id: "nl",
    name: "Netherlands",
    kind: "country",
    lon: 5.29,
    lat: 52.13,
    bbox: [3.36, 50.75, 7.23, 53.56],
    country: "NL",
    aliases: [
      { name: "Holland", kind: "colloquial" },
      { name: "Nederland", kind: "endonym" },
    ],
    population: 17_900_000,
    note: "Holland is two of its twelve provinces. Users mean the country; a gazetteer that matches the string exactly gives them a third of it.",
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    kind: "country",
    lon: 54.0,
    lat: 24.0,
    bbox: [51.5, 22.6, 56.4, 26.08],
    country: "AE",
    aliases: [{ name: "UAE", kind: "abbreviation" }],
    population: 10_200_000,
  },
  {
    id: "ge-country",
    name: "Georgia",
    kind: "country",
    lon: 43.36,
    lat: 42.32,
    bbox: [39.99, 41.05, 46.72, 43.59],
    country: "GE",
    aliases: [{ name: "საქართველო", kind: "endonym" }],
    ambiguousWith: ["us-ga"],
    population: 3_700_000,
    note: "A country and a US state share this name exactly. There is no spelling that distinguishes them and the two are 9,000 km apart, so a ranker that quietly prefers one is wrong half the time with total confidence.",
  },
  {
    id: "tr",
    name: "Türkiye",
    kind: "country",
    lon: 35.24,
    lat: 38.96,
    bbox: [25.66, 35.82, 44.83, 42.11],
    country: "TR",
    aliases: [
      { name: "Turkey", kind: "former" },
      { name: "Turkiye", kind: "colloquial" },
    ],
    population: 85_300_000,
    note: "Renamed at the UN in 2022, so both spellings are live, and the old one is also a bird and a common false positive in any free-text place matcher.",
  },
  {
    id: "sg",
    name: "Singapore",
    kind: "country",
    lon: 103.82,
    lat: 1.352,
    bbox: [103.6, 1.16, 104.09, 1.47],
    country: "SG",
    population: 5_900_000,
    note: "A city and a country with the same name and the same boundary, so \"in Singapore\" is simultaneously a city query and a country query and the two should return the same rows.",
  },

  /* ── Regions and states ────────────────────────────────────────────────── */
  {
    id: "us-ga",
    name: "Georgia",
    kind: "region",
    lon: -83.44,
    lat: 32.68,
    bbox: [-85.61, 30.36, -80.84, 35.0],
    country: "US",
    within: "us",
    ambiguousWith: ["ge-country"],
    population: 11_100_000,
  },
  {
    id: "us-ca",
    name: "California",
    kind: "region",
    lon: -119.42,
    lat: 36.78,
    bbox: [-124.41, 32.53, -114.13, 42.01],
    country: "US",
    within: "us",
    aliases: [{ name: "CA", kind: "abbreviation" }],
    population: 39_000_000,
    note: "\"CA\" is also the ISO code for Canada, so the two-letter form resolves to a country nineteen times the size.",
  },
  {
    id: "gb-scotland",
    name: "Scotland",
    kind: "region",
    lon: -4.2,
    lat: 56.49,
    bbox: [-7.69, 54.63, -0.72, 60.86],
    country: "GB",
    within: "gb",
    aliases: [{ name: "Alba", kind: "endonym" }],
    population: 5_500_000,
  },
  {
    id: "de-bayern",
    name: "Bavaria",
    kind: "region",
    lon: 11.5,
    lat: 48.79,
    bbox: [8.98, 47.27, 13.84, 50.56],
    country: "DE",
    within: "de",
    aliases: [{ name: "Bayern", kind: "endonym" }],
    population: 13_400_000,
  },
  {
    id: "jp-kansai",
    name: "Kansai",
    kind: "region",
    lon: 135.5,
    lat: 34.7,
    bbox: [134.2, 33.4, 136.98, 35.78],
    country: "JP",
    within: "jp",
    aliases: [{ name: "Kinki", kind: "endonym" }],
    population: 22_000_000,
    note: "An informal region with no administrative boundary, so two gazetteers give two different polygons and neither is wrong.",
  },
  {
    id: "nz-south",
    name: "South Island",
    kind: "region",
    lon: 170.5,
    lat: -43.6,
    bbox: [166.43, -47.29, 174.4, -40.44],
    country: "NZ",
    within: "nz",
    aliases: [{ name: "Te Waipounamu", kind: "endonym" }],
    population: 1_200_000,
  },

  /* ── Cities ────────────────────────────────────────────────────────────── */
  {
    id: "tokyo",
    name: "Tokyo",
    kind: "city",
    lon: 139.6917,
    lat: 35.6895,
    bbox: [139.56, 35.52, 139.92, 35.82],
    country: "JP",
    within: "jp",
    aliases: [{ name: "東京", kind: "endonym" }],
    population: 13_960_000,
    note: "Tokyo Metropolis legally includes the Ogasawara Islands, 1,000 km south. Filter by the prefecture and you get devices in the Pacific; filter by the 23 wards and you drop them.",
  },
  {
    id: "kyoto",
    name: "Kyoto",
    kind: "city",
    lon: 135.7681,
    lat: 35.0116,
    bbox: [135.6, 34.87, 135.88, 35.19],
    country: "JP",
    within: "jp-kansai",
    aliases: [{ name: "京都", kind: "endonym" }],
    population: 1_460_000,
    note: "One transposed vowel from Tokyo, 370 km away. Every fuzzy matcher with an edit distance of two will offer you the other one.",
  },
  {
    id: "osaka",
    name: "Osaka",
    kind: "city",
    lon: 135.5023,
    lat: 34.6937,
    bbox: [135.4, 34.58, 135.62, 34.79],
    country: "JP",
    within: "jp-kansai",
    aliases: [{ name: "大阪", kind: "endonym" }, { name: "Ōsaka", kind: "endonym" }],
    population: 2_750_000,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    kind: "city",
    lon: -9.1393,
    lat: 38.7223,
    bbox: [-9.23, 38.69, -9.09, 38.8],
    country: "PT",
    within: "pt",
    aliases: [{ name: "Lisboa", kind: "endonym" }],
    population: 545_000,
  },
  {
    id: "london",
    name: "London",
    kind: "city",
    lon: -0.1276,
    lat: 51.5072,
    bbox: [-0.51, 51.29, 0.33, 51.69],
    country: "GB",
    within: "gb",
    aliases: [{ name: "LDN", kind: "abbreviation" }],
    ambiguousWith: ["london-on"],
    population: 8_900_000,
  },
  {
    id: "london-on",
    name: "London",
    kind: "city",
    lon: -81.2497,
    lat: 42.9849,
    bbox: [-81.4, 42.88, -81.1, 43.07],
    country: "CA",
    aliases: [{ name: "London, Ontario", kind: "colloquial" }],
    ambiguousWith: ["london"],
    population: 423_000,
    note: "Population ranking hides this one until a Canadian customer files the bug.",
  },
  {
    id: "paris",
    name: "Paris",
    kind: "city",
    lon: 2.3522,
    lat: 48.8566,
    bbox: [2.22, 48.81, 2.47, 48.91],
    country: "FR",
    within: "fr",
    ambiguousWith: ["paris-tx"],
    population: 2_100_000,
  },
  {
    id: "paris-tx",
    name: "Paris",
    kind: "city",
    lon: -95.5555,
    lat: 33.6609,
    bbox: [-95.62, 33.6, -95.47, 33.72],
    country: "US",
    within: "us",
    ambiguousWith: ["paris"],
    population: 24_800,
  },
  {
    id: "cambridge",
    name: "Cambridge",
    kind: "city",
    lon: 0.1218,
    lat: 52.2053,
    bbox: [0.06, 52.16, 0.19, 52.25],
    country: "GB",
    within: "gb",
    ambiguousWith: ["cambridge-ma"],
    population: 145_000,
  },
  {
    id: "cambridge-ma",
    name: "Cambridge",
    kind: "city",
    lon: -71.1097,
    lat: 42.3736,
    bbox: [-71.16, 42.35, -71.06, 42.4],
    country: "US",
    within: "us",
    ambiguousWith: ["cambridge"],
    population: 118_000,
    note: "Two university cities 5,000 km apart with near-identical populations, so there is no ranking signal to break the tie with. This is the one that catches \"pick the biggest\".",
  },
  {
    id: "newcastle",
    name: "Newcastle",
    kind: "city",
    lon: -1.6132,
    lat: 54.9783,
    bbox: [-1.75, 54.93, -1.5, 55.05],
    country: "GB",
    within: "gb",
    aliases: [{ name: "Newcastle upon Tyne", kind: "endonym" }],
    ambiguousWith: ["newcastle-au"],
    population: 300_000,
  },
  {
    id: "newcastle-au",
    name: "Newcastle",
    kind: "city",
    lon: 151.7817,
    lat: -32.9283,
    bbox: [151.66, -33.03, 151.86, -32.83],
    country: "AU",
    within: "au",
    ambiguousWith: ["newcastle"],
    population: 322_000,
  },
  {
    id: "sanjose",
    name: "San Jose",
    kind: "city",
    lon: -121.8863,
    lat: 37.3382,
    bbox: [-122.05, 37.2, -121.75, 37.47],
    country: "US",
    within: "us-ca",
    aliases: [{ name: "San José", kind: "endonym" }],
    ambiguousWith: ["sanjose-cr"],
    population: 970_000,
  },
  {
    id: "sanjose-cr",
    name: "San José",
    kind: "city",
    lon: -84.0907,
    lat: 9.9281,
    bbox: [-84.16, 9.88, -84.02, 9.98],
    country: "CR",
    ambiguousWith: ["sanjose"],
    population: 342_000,
    note: "The accent is the only thing between the two, and it is the first thing an ASCII-folding index throws away.",
  },
  {
    id: "auckland",
    name: "Auckland",
    kind: "city",
    lon: 174.7633,
    lat: -36.8485,
    bbox: [174.5, -37.05, 175.0, -36.68],
    country: "NZ",
    within: "nz",
    aliases: [{ name: "Tāmaki Makaurau", kind: "endonym" }],
    population: 1_460_000,
  },
  {
    id: "wellington",
    name: "Wellington",
    kind: "city",
    lon: 174.7762,
    lat: -41.2865,
    bbox: [174.69, -41.36, 174.86, -41.21],
    country: "NZ",
    within: "nz",
    aliases: [{ name: "Te Whanganui-a-Tara", kind: "endonym" }],
    population: 217_000,
  },
  {
    id: "munich",
    name: "Munich",
    kind: "city",
    lon: 11.582,
    lat: 48.1351,
    bbox: [11.36, 48.06, 11.72, 48.25],
    country: "DE",
    within: "de-bayern",
    aliases: [{ name: "München", kind: "endonym" }, { name: "Muenchen", kind: "colloquial" }],
    population: 1_490_000,
    note: "Three spellings in live use — Munich, München, Muenchen — and a user typing any of them expects the same rows back.",
  },
  {
    id: "cologne",
    name: "Cologne",
    kind: "city",
    lon: 6.9603,
    lat: 50.9375,
    bbox: [6.77, 50.83, 7.16, 51.08],
    country: "DE",
    within: "de",
    aliases: [{ name: "Köln", kind: "endonym" }, { name: "Koeln", kind: "colloquial" }],
    population: 1_080_000,
  },
  {
    id: "florence",
    name: "Florence",
    kind: "city",
    lon: 11.2558,
    lat: 43.7696,
    bbox: [11.15, 43.72, 11.33, 43.83],
    country: "IT",
    aliases: [{ name: "Firenze", kind: "endonym" }],
    population: 361_000,
    note: "The English name and the local name share no substring at all, so a prefix index finds neither from the other.",
  },
  {
    id: "vienna",
    name: "Vienna",
    kind: "city",
    lon: 16.3738,
    lat: 48.2082,
    bbox: [16.18, 48.12, 16.58, 48.32],
    country: "AT",
    aliases: [{ name: "Wien", kind: "endonym" }],
    population: 1_980_000,
  },
  {
    id: "saopaulo",
    name: "São Paulo",
    kind: "city",
    lon: -46.6333,
    lat: -23.5505,
    bbox: [-46.83, -23.82, -46.36, -23.36],
    country: "BR",
    within: "br",
    aliases: [{ name: "Sao Paulo", kind: "colloquial" }],
    population: 12_300_000,
    note: "Almost nobody types the tilde. If the index is not folded, the correct spelling and the typed one are different strings.",
  },
  {
    id: "zurich",
    name: "Zürich",
    kind: "city",
    lon: 8.5417,
    lat: 47.3769,
    bbox: [8.45, 47.32, 8.63, 47.43],
    country: "CH",
    aliases: [{ name: "Zurich", kind: "colloquial" }, { name: "Zuerich", kind: "colloquial" }],
    population: 435_000,
  },
  {
    id: "mumbai",
    name: "Mumbai",
    kind: "city",
    lon: 72.8777,
    lat: 19.076,
    bbox: [72.77, 18.89, 72.99, 19.28],
    country: "IN",
    aliases: [{ name: "Bombay", kind: "former" }],
    population: 12_400_000,
    note: "Renamed in 1995, and thirty years on the old name is still in half the address data your users paste in.",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    kind: "city",
    lon: 28.9784,
    lat: 41.0082,
    bbox: [28.6, 40.8, 29.4, 41.24],
    country: "TR",
    within: "tr",
    aliases: [
      { name: "İstanbul", kind: "endonym" },
      { name: "Constantinople", kind: "former" },
    ],
    population: 15_600_000,
    note: "The Turkish dotted capital İ lowercases to i̇ under the invariant rules and to ı under Turkish ones, so a case-insensitive match works or fails depending on the server's locale.",
  },
  {
    id: "newyork",
    name: "New York",
    kind: "city",
    lon: -74.006,
    lat: 40.7128,
    bbox: [-74.26, 40.49, -73.7, 40.92],
    country: "US",
    within: "us",
    aliases: [
      { name: "NYC", kind: "abbreviation" },
      { name: "New York City", kind: "colloquial" },
      { name: "JFK", kind: "code" },
    ],
    population: 8_300_000,
    note: "The city sits inside a state of the same name that is 400 km across. \"Devices in New York\" is two different queries and the string cannot tell you which.",
  },
  {
    id: "sanfrancisco",
    name: "San Francisco",
    kind: "city",
    lon: -122.4194,
    lat: 37.7749,
    bbox: [-122.52, 37.7, -122.35, 37.83],
    country: "US",
    within: "us-ca",
    aliases: [{ name: "SF", kind: "abbreviation" }, { name: "SFO", kind: "code" }],
    population: 810_000,
  },
  {
    id: "losangeles",
    name: "Los Angeles",
    kind: "city",
    lon: -118.2437,
    lat: 34.0522,
    bbox: [-118.67, 33.7, -118.16, 34.34],
    country: "US",
    within: "us-ca",
    aliases: [{ name: "LA", kind: "abbreviation" }, { name: "LAX", kind: "code" }],
    population: 3_820_000,
    note: "\"LA\" is also the state code for Louisiana, 2,500 km away, and a common word in three other languages.",
  },
  {
    id: "mexicocity",
    name: "Mexico City",
    kind: "city",
    lon: -99.1332,
    lat: 19.4326,
    bbox: [-99.36, 19.05, -98.94, 19.59],
    country: "MX",
    aliases: [
      { name: "Ciudad de México", kind: "endonym" },
      { name: "CDMX", kind: "abbreviation" },
      { name: "México D.F.", kind: "former" },
    ],
    population: 9_200_000,
  },
  {
    id: "dubai",
    name: "Dubai",
    kind: "city",
    lon: 55.2708,
    lat: 25.2048,
    bbox: [54.9, 24.79, 55.56, 25.35],
    country: "AE",
    within: "ae",
    aliases: [{ name: "دبي", kind: "endonym" }],
    population: 3_600_000,
  },
  {
    id: "sydney",
    name: "Sydney",
    kind: "city",
    lon: 151.2093,
    lat: -33.8688,
    bbox: [150.52, -34.12, 151.34, -33.58],
    country: "AU",
    within: "au",
    ambiguousWith: ["sydney-ns"],
    population: 5_300_000,
  },
  {
    id: "sydney-ns",
    name: "Sydney",
    kind: "city",
    lon: -60.1831,
    lat: 46.1368,
    bbox: [-60.27, 46.09, -60.1, 46.19],
    country: "CA",
    ambiguousWith: ["sydney"],
    population: 30_000,
    note: "Nova Scotia. Antipodal enough to the Australian one that a swapped sign in a bbox filter lands you here and looks plausible.",
  },
  {
    id: "mobile",
    name: "Mobile",
    kind: "city",
    lon: -88.0399,
    lat: 30.6954,
    bbox: [-88.25, 30.56, -87.94, 30.83],
    country: "US",
    within: "us",
    population: 184_000,
    note: "A city whose name is an ordinary adjective and a device category at once. \"Show me mobile devices in Mobile\" is a real query and only one of those two words is a place.",
  },
  {
    id: "nice",
    name: "Nice",
    kind: "city",
    lon: 7.2619,
    lat: 43.7102,
    bbox: [7.19, 43.65, 7.32, 43.77],
    country: "FR",
    within: "fr",
    aliases: [{ name: "Nizza", kind: "exonym" }],
    population: 342_000,
    note: "Also an English adjective, so a place matcher scanning free text finds it in \"nice work\" and puts your devices on the Côte d'Azur.",
  },
  {
    id: "split",
    name: "Split",
    kind: "city",
    lon: 16.4402,
    lat: 43.5081,
    bbox: [16.36, 43.46, 16.53, 43.55],
    country: "HR",
    population: 160_000,
    note: "Also a verb, a noun, and a method on every string type in existence. It reaches your place matcher inside sentences that have nothing to do with Croatia.",
  },
  {
    id: "reading",
    name: "Reading",
    kind: "city",
    lon: -0.9781,
    lat: 51.4543,
    bbox: [-1.06, 51.41, -0.9, 51.49],
    country: "GB",
    within: "gb",
    population: 175_000,
    note: "A gerund with a town attached. Any free-text extractor that is not part-of-speech aware finds it in \"reading the manifest\".",
  },

  /* ── Venues ────────────────────────────────────────────────────────────── */
  {
    id: "estadio-da-luz",
    name: "Estádio da Luz",
    kind: "venue",
    lon: -9.1847,
    lat: 38.7526,
    bbox: site(-9.1847, 38.7526, 0.3),
    country: "PT",
    within: "lisbon",
    aliases: [
      { name: "Estadio da Luz", kind: "colloquial" },
      { name: "Estádio do Sport Lisboa e Benfica", kind: "endonym" },
      { name: "Benfica stadium", kind: "colloquial" },
    ],
    note: "Two accents and a Portuguese article that English speakers reliably render as \"de\". Every one of \"Estadio de Luz\", \"Estádio da Luz\" and \"the Luz\" means this building.",
  },
  {
    id: "wembley",
    name: "Wembley Stadium",
    kind: "venue",
    lon: -0.2795,
    lat: 51.556,
    bbox: site(-0.2795, 51.556, 0.3),
    country: "GB",
    within: "london",
    aliases: [{ name: "Wembley", kind: "colloquial" }],
    note: "\"Wembley\" on its own is also the surrounding district, several square kilometres larger than the stadium. Which one you resolve to changes the answer by an order of magnitude.",
  },
  {
    id: "emirates-stadium",
    name: "Emirates Stadium",
    kind: "venue",
    lon: -0.1084,
    lat: 51.5549,
    bbox: site(-0.1084, 51.5549, 0.25),
    country: "GB",
    within: "london",
    aliases: [{ name: "Arsenal Stadium", kind: "colloquial" }],
    note: "A sponsor name that has changed before and will change again, and one that collides with an airline, a country and an airport in the same index.",
  },
  {
    id: "camp-nou",
    name: "Camp Nou",
    kind: "venue",
    lon: 2.1228,
    lat: 41.3809,
    bbox: site(2.1228, 41.3809, 0.3),
    country: "ES",
    within: "barcelona",
    aliases: [{ name: "Nou Camp", kind: "colloquial" }],
    note: "Half the English-speaking world types the two words in the wrong order, and \"Nou Camp\" is not a string edit away from the right one in most tokenisers.",
  },
  {
    id: "bernabeu",
    name: "Santiago Bernabéu",
    kind: "venue",
    lon: -3.6883,
    lat: 40.4531,
    bbox: site(-3.6883, 40.4531, 0.25),
    country: "ES",
    within: "madrid",
    aliases: [{ name: "Estadio Santiago Bernabeu", kind: "colloquial" }],
    note: "Shares its first word with a capital city 10,000 km away, so a matcher that scores on any token hit puts this in Chile.",
  },
  {
    id: "allianz-arena",
    name: "Allianz Arena",
    kind: "venue",
    lon: 11.6247,
    lat: 48.2188,
    bbox: site(11.6247, 48.2188, 0.3),
    country: "DE",
    within: "munich",
  },
  {
    id: "tokyo-skytree",
    name: "Tokyo Skytree",
    kind: "venue",
    lon: 139.8107,
    lat: 35.7101,
    bbox: site(139.8107, 35.7101, 0.2),
    country: "JP",
    within: "tokyo",
    aliases: [{ name: "東京スカイツリー", kind: "endonym" }, { name: "Sky Tree", kind: "colloquial" }],
    note: "Contains the name of its own city, so a matcher that strips the venue and keeps the city gets the right answer for the wrong reason — and gets 13 million people's worth of extra devices.",
  },
  {
    id: "shibuya-crossing",
    name: "Shibuya Crossing",
    kind: "venue",
    lon: 139.7005,
    lat: 35.6595,
    bbox: site(139.7005, 35.6595, 0.15),
    country: "JP",
    within: "tokyo",
    aliases: [{ name: "Shibuya Scramble", kind: "colloquial" }],
    note: "An intersection, not a building. It has no official boundary at all, so \"in Shibuya Crossing\" needs a radius somebody chose.",
  },
  {
    id: "fushimi-inari",
    name: "Fushimi Inari-taisha",
    kind: "venue",
    lon: 135.7727,
    lat: 34.9671,
    bbox: site(135.7727, 34.9671, 0.8),
    country: "JP",
    within: "kyoto",
    aliases: [{ name: "Fushimi Inari", kind: "colloquial" }, { name: "伏見稲荷大社", kind: "endonym" }],
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    kind: "venue",
    lon: 2.2945,
    lat: 48.8584,
    bbox: site(2.2945, 48.8584, 0.2),
    country: "FR",
    within: "paris",
    aliases: [{ name: "Tour Eiffel", kind: "endonym" }],
  },
  {
    id: "brandenburg-gate",
    name: "Brandenburg Gate",
    kind: "venue",
    lon: 13.3777,
    lat: 52.5163,
    bbox: site(13.3777, 52.5163, 0.15),
    country: "DE",
    within: "berlin",
    aliases: [{ name: "Brandenburger Tor", kind: "endonym" }],
  },
  {
    id: "times-square",
    name: "Times Square",
    kind: "venue",
    lon: -73.9855,
    lat: 40.758,
    bbox: site(-73.9855, 40.758, 0.25),
    country: "US",
    within: "newyork",
    note: "Two of the commonest words in English sitting next to each other. Quoting is the only thing that keeps it out of a full-text query's noise.",
  },
  {
    id: "golden-gate",
    name: "Golden Gate Bridge",
    kind: "venue",
    lon: -122.4783,
    lat: 37.8199,
    bbox: site(-122.4783, 37.8199, 1.5),
    country: "US",
    within: "sanfrancisco",
    note: "2.7 km long and 27 m wide. A point-radius match around its centroid misses both ends of it.",
  },
  {
    id: "opera-house",
    name: "Sydney Opera House",
    kind: "venue",
    lon: 151.2153,
    lat: -33.8568,
    bbox: site(151.2153, -33.8568, 0.2),
    country: "AU",
    within: "sydney",
  },
  {
    id: "eden-park",
    name: "Eden Park",
    kind: "venue",
    lon: 174.7448,
    lat: -36.8748,
    bbox: site(174.7448, -36.8748, 0.3),
    country: "NZ",
    within: "auckland",
  },
  {
    id: "burj-khalifa",
    name: "Burj Khalifa",
    kind: "venue",
    lon: 55.2744,
    lat: 25.1972,
    bbox: site(55.2744, 25.1972, 0.2),
    country: "AE",
    within: "dubai",
    note: "828 m of it is vertical. Every device inside shares one footprint, and a floor is the only thing that separates them.",
  },
  {
    id: "marina-bay-sands",
    name: "Marina Bay Sands",
    kind: "venue",
    lon: 103.8607,
    lat: 1.2834,
    bbox: site(103.8607, 1.2834, 0.4),
    country: "SG",
    within: "sg",
  },
  {
    id: "heathrow",
    name: "Heathrow Airport",
    kind: "venue",
    lon: -0.4543,
    lat: 51.47,
    bbox: [-0.5, 51.448, -0.41, 51.492],
    country: "GB",
    within: "london",
    aliases: [
      { name: "LHR", kind: "code" },
      { name: "London Heathrow", kind: "colloquial" },
    ],
    note: "\"London Heathrow\" contains a city name 25 km away, and LHR is three letters that also appear as a column header, a status code and an initialism in half the datasets it lands in.",
  },
  {
    id: "haneda",
    name: "Haneda Airport",
    kind: "venue",
    lon: 139.7798,
    lat: 35.5494,
    bbox: [139.74, 35.53, 139.83, 35.58],
    country: "JP",
    within: "tokyo",
    aliases: [
      { name: "HND", kind: "code" },
      { name: "Tokyo International Airport", kind: "endonym" },
    ],
    note: "Its official name is Tokyo International Airport, which is also what people call Narita, 60 km in the other direction.",
  },
  {
    id: "lisbon-airport",
    name: "Humberto Delgado Airport",
    kind: "venue",
    lon: -9.1342,
    lat: 38.7742,
    bbox: [-9.16, 38.76, -9.11, 38.79],
    country: "PT",
    within: "lisbon",
    aliases: [
      { name: "LIS", kind: "code" },
      { name: "Lisbon Airport", kind: "colloquial" },
      { name: "Portela", kind: "former" },
    ],
  },

  /* ── Cities that exist here only to be somewhere else's parent ─────────── */
  {
    id: "barcelona",
    name: "Barcelona",
    kind: "city",
    lon: 2.1734,
    lat: 41.3851,
    bbox: [2.05, 41.32, 2.23, 41.47],
    country: "ES",
    population: 1_620_000,
  },
  {
    id: "madrid",
    name: "Madrid",
    kind: "city",
    lon: -3.7038,
    lat: 40.4168,
    bbox: [-3.89, 40.31, -3.52, 40.64],
    country: "ES",
    population: 3_280_000,
  },
  {
    id: "berlin",
    name: "Berlin",
    kind: "city",
    lon: 13.405,
    lat: 52.52,
    bbox: [13.09, 52.34, 13.76, 52.68],
    country: "DE",
    within: "de",
    population: 3_670_000,
  },
  /* ── Names with an apostrophe in them ──────────────────────────────────── */
  {
    id: "oconnell-street",
    name: "O'Connell Street",
    kind: "venue",
    lon: -6.2603,
    lat: 53.3498,
    bbox: [-6.2632, 53.3472, -6.2578, 53.3525],
    country: "IE",
    within: "dublin",
    note: "A perfectly ordinary street name that ends a SQL string literal early, and a JSON string too if the escaping was done by hand.",
  },
  {
    id: "dublin",
    name: "Dublin",
    kind: "city",
    lon: -6.2603,
    lat: 53.3498,
    bbox: [-6.39, 53.28, -6.11, 53.41],
    country: "IE",
    population: 592_000,
    ambiguousWith: ["dublin-oh"],
  },
  {
    id: "dublin-oh",
    name: "Dublin",
    kind: "city",
    lon: -83.1141,
    lat: 40.0992,
    bbox: [-83.19, 40.05, -83.03, 40.17],
    country: "US",
    within: "us",
    ambiguousWith: ["dublin"],
    population: 49_000,
  },
  {
    id: "ndjamena",
    name: "N'Djamena",
    kind: "city",
    lon: 15.0557,
    lat: 12.1348,
    bbox: [14.98, 12.06, 15.13, 12.2],
    country: "TD",
    population: 1_600_000,
    note: "An apostrophe in the second character. Anything that quotes by wrapping in single quotes produces a syntax error before it produces a result.",
  },
  {
    id: "coeur-dalene",
    name: "Coeur d'Alene",
    kind: "city",
    lon: -116.7805,
    lat: 47.6777,
    bbox: [-116.85, 47.63, -116.71, 47.73],
    country: "US",
    within: "us",
    aliases: [{ name: "Coeur dAlene", kind: "colloquial" }],
    population: 56_000,
  },
  {
    id: "shertogenbosch",
    name: "'s-Hertogenbosch",
    kind: "city",
    lon: 5.3037,
    lat: 51.6978,
    bbox: [5.24, 51.65, 5.37, 51.74],
    country: "NL",
    within: "nl",
    aliases: [{ name: "Den Bosch", kind: "colloquial" }],
    population: 157_000,
    note: "Starts with an apostrophe. Sorting, trimming, capitalising and quoting all do something surprising to it, and every one of them is somebody's idea of normalisation.",
  },
];

const BY_ID = new Map(PLACES.map((p) => [p.id, p]));

export function getPlace(id: string): Place | undefined {
  return BY_ID.get(id);
}

export function placesOfKind(kind: PlaceKind): Place[] {
  return PLACES.filter((p) => p.kind === kind);
}

/** Every name this place answers to, canonical first. */
export function allNames(place: Place): string[] {
  return [place.name, ...(place.aliases ?? []).map((a) => a.name)];
}

/** An alias of a particular kind, when this place has one. */
export function aliasOfKind(place: Place, kind: AliasKind): Alias | undefined {
  return place.aliases?.find((a) => a.kind === kind);
}

/** The chain outwards: a venue, then its city, then its country. */
export function containers(place: Place): Place[] {
  const chain: Place[] = [];
  let current = place.within ? BY_ID.get(place.within) : undefined;
  // Bounded rather than while(true): a bad `within` cycle in the data would
  // otherwise hang the generator instead of producing a wrong term.
  for (let depth = 0; current && depth < 4; depth++) {
    chain.push(current);
    current = current.within ? BY_ID.get(current.within) : undefined;
  }
  return chain;
}

/**
 * Places whose name is also an ordinary word. Kept as a list rather than a flag
 * because the interesting thing about them is the sentence they hide in, and
 * that belongs beside the query builder rather than in the gazetteer.
 */
export const WORD_PLACES = ["mobile", "nice", "split", "reading"];

/**
 * Places whose real, correct name contains an apostrophe. Not adversarial
 * input — just names — which is precisely why they get through the filter that
 * was written to stop adversarial input.
 */
export const QUOTED_PLACES = ["oconnell-street", "ndjamena", "coeur-dalene", "shertogenbosch"];

/** Names that resolve to nothing. The right answer to these is zero rows. */
export const UNKNOWN_PLACES = [
  "Northwich Vale",
  "Port Halloran",
  "Sankt Brevik",
  "Eastmarch",
  "Villa Corrientes del Sur",
  "Old Kettering Wharf",
  "Nuevo Tandil Alto",
];
