import { group, formatBytes } from "./format";
import { getProfile } from "./profiles/index";
import { SITE_HOST } from "./site";
import type { GeneratedFile } from "./types";

/**
 * What a file *is*, written for something that cannot see the map.
 *
 * The same block is rendered on screen, copied to the clipboard, and written
 * into a package README — built once as structure so those three can never
 * drift apart.
 *
 * A clean file gets a different account of itself, not a softer one. Handing
 * over a valid control case under the words "deliberately broken" and "known
 * problems baked into this file" would be the tool lying about its own output
 * to whoever — or whatever — reads this block downstream.
 */
export interface ContextBlock {
  intro: string;
  fields: Array<[string, string]>;
  /**
   * The checks that established a clean file really is one. Null for a file
   * with problems in it, where the question does not arise.
   */
  checks: { heading: string; lines: string[] } | null;
  heading: string;
  problems: string[];
}

export function buildContext(file: GeneratedFile, formatLabel: string): ContextBlock {
  const profile = getProfile(file.stats.profile);
  const clean = file.stats.clean;
  const fields: Array<[string, string]> = [
    ["File", file.filename],
    ["Format", formatLabel],
    // A data type's blurb is an account of the trouble it causes — "the floor
    // label is 'G' on one row and '0' on the next". True of the feed, and not
    // true of a clean file wearing its schema, so a control case is named
    // rather than characterised. What it actually holds is in the notes.
    [
      "Data type",
      clean || profile.family === "generic" ? profile.label : `${profile.label} — ${profile.blurb}`,
    ],
    ["Size", formatBytes(file.bytes)],
    ["Features", group(file.stats.features)],
    ["Positions", group(file.map.total)],
  ];

  if (file.map.bbox) {
    const [minX, minY, maxX, maxY] = file.map.bbox;
    fields.push(["Bounds", `${minX}, ${minY} to ${maxX}, ${maxY}`]);
  }
  if (file.map.outOfRange || file.map.invalid) {
    fields.push([
      "Off-world",
      `${group(file.map.outOfRange + file.map.invalid)} positions` +
        (file.map.invalid ? ` (${group(file.map.invalid)} not a number)` : ""),
    ]);
  }

  if (!clean) {
    return {
      intro: `This is a deliberately broken geospatial test fixture, generated by Null Island (${SITE_HOST}).`,
      fields,
      checks: null,
      heading: "Known problems baked into this file:",
      problems: file.notes.length
        ? file.notes
        : ["None. This is a clean, well-formed file, useful as a control case."],
    };
  }

  const report = file.clean;
  return {
    intro:
      `This is a clean geospatial test fixture, generated by Null Island (${SITE_HOST}). ` +
      "Nothing is wrong with it on purpose: it is the control case. If your map cannot " +
      "load this file, the fault is on the reading side, not in the data.",
    fields,
    checks: report
      ? {
          heading: report.passed
            ? "Checked on this file before it was handed over:"
            : "This file FAILED its own clean check — that is a bug in Null Island:",
          lines: report.checks.map(
            (check) => `${check.ok ? "" : "FAILED — "}${check.label} (${check.detail}).`,
          ),
        }
      : null,
    heading: "Worth knowing about this file:",
    // The notes on a clean file are not problems. They are what the format
    // could not carry and what the data type does of its own accord — a GPX
    // with no attributes is still a clean GPX, and a reader that loses them
    // has lost them to the container, not to a fixture playing tricks.
    problems: file.notes.length
      ? file.notes
      : ["Nothing. Every attribute and every geometry survived into the file as generated."],
  };
}

export function contextToText(block: ContextBlock): string {
  return [
    block.intro,
    "",
    ...block.fields.map(([label, value]) => `${label}: ${value}`),
    ...(block.checks
      ? ["", block.checks.heading, ...block.checks.lines.map((line) => `- ${line}`)]
      : []),
    "",
    block.heading,
    ...block.problems.map((p) => `- ${p}`),
  ].join("\n");
}
