import type { DataProfile } from "./index";

/**
 * Observations of the planet, as the vector products they actually ship as.
 *
 * There is no raster pipeline here — these are the footprints, contours,
 * station points and class polygons that arrive alongside the imagery. Their
 * family trait is scale confusion: NDVI as a fraction or as an integer, cloud
 * cover as a percentage or a ratio, heights in feet or metres, and a nodata
 * sentinel sitting in a numeric column pretending to be a measurement.
 */
export const EARTH_PROFILES: DataProfile[] = [
  {
    id: "satellite-scene-footprints",
    label: "Satellite & aerial imagery",
    family: "earth",
    blurb: "Scene footprints with STAC-style capture metadata. Cloud cover is a 0–1 fraction on one row and a percentage on the next, and the polygon is the whole tile even where 8% of it has pixels.",
    geometry: "tile",
    fields: [
      {
        name: "scene_id",
        type: "string",
        example: "LC09_L2SP_203024_20240317_20240329_02_T1",
        note: "Carries path/row plus both an acquisition date and a processing date. The second one changes on reprocessing, so sorting by scene_id does not sort by image age.",
      },
      {
        name: "platform",
        type: "string",
        values: ["LANDSAT_8","LANDSAT_9","SENTINEL-2A","SENTINEL-2B","WV03","GE01","PHR1B","N856MA"],
        note: "Underscores from USGS, a hyphen from ESA, four characters from Maxar and Airbus, and an aircraft registration where the row is aerial. Group by platform and you get one bucket per provider's naming habit.",
      },
      {
        name: "instrument",
        type: "string",
        values: ["OLI_TIRS","MSI","TIRS","VNIR","PAN","C-SAR"],
        note: "OLI_TIRS is two sensors in one value, and rows that used only the thermal bands still say OLI_TIRS. In STAC this is a list, so a flattened export holds either the first element or a joined string.",
      },
      {
        name: "acquisition_datetime",
        type: "iso-datetime",
        example: "2024-03-17T10:42:31.024Z",
        note: "Scene-centre time on optical rows and local solar time on a few older aerial catalogues — same column, and the aerial ones carry no offset. Sentinel-2 keeps milliseconds, Landsat does not.",
      },
      {
        name: "tile_id",
        type: "string",
        example: "T31UCU",
        note: "MGRS tile on Sentinel-2 rows and zero-padded WRS-2 path/row ('203024') on Landsat ones, in one column. Typed as a number anywhere in the chain, '024' becomes 24 and the join to the grid table finds nothing.",
      },
      {
        name: "cloud_cover",
        type: "float",
        example: "12.4",
        min: 0,
        max: 100,
        nullable: true,
        note: "A percentage from most providers and a 0–1 fraction from a few, with -1 where the mask never ran. In STAC the key is 'eo:cloud_cover', so a shapefile export truncates it to CLOUD_COVE and a CSV keeps the colon. Unit: %.",
      },
      {
        name: "sun_elevation",
        type: "float",
        example: "38.6",
        min: 12,
        max: 78,
        nullable: true,
        note: "Elevation above the horizon, except where an exporter wrote solar zenith into it. 38.6 and 51.4 are then the same scene. Unit: degrees.",
      },
      {
        name: "off_nadir",
        type: "float",
        example: "14.2",
        min: 0,
        max: 32,
        nullable: true,
        note: "Blank on nadir-only sensors. A high off-nadir row has real geometric distortion and a coarser true GSD than gsd_m claims, and the footprint polygon shows neither. Unit: degrees.",
      },
      {
        name: "gsd_m",
        type: "float",
        example: "0.46",
        min: 0.3,
        max: 30,
        note: "Metres in the name, centimetres in the value on some high-resolution rows: 31 and 0.31 are the same sensor. The value is the nadir figure even where off_nadir says 30°. Unit: m.",
      },
      {
        name: "processing_level",
        type: "string",
        values: ["L1C","L2A","L1TP","L1GT","L1GS","L2SP","ORTHO","RAW"],
        note: "Each provider's ladder is different. L1TP and L1C are comparable; L1GS and RAW are not orthorectified at all, and their footprints are the least trustworthy in the file.",
      },
      {
        name: "proj_epsg",
        type: "int",
        example: "32631",
        min: 32601,
        max: 32660,
        note: "The UTM zone the pixels sit in — 'proj:epsg' in STAC. The footprint in the file is WGS84 regardless, so a reader that honours this column reprojects an already-geographic polygon.",
      },
      {
        name: "product_uri",
        type: "string",
        literal: true,
        example: "S2B_MSIL2A_20240317T104629_N0510_R051_T31UCU_20240317T134221.SAFE",
        note: "65 characters, and the only field separating two reprocessings of one acquisition. Shapefile cuts the field name to PRODUCT_UR and the DBF character width cuts the value.",
      },
      {
        name: "data_coverage",
        type: "float",
        example: "88.3",
        min: 55,
        max: 100,
        nullable: true,
        note: "The share of the footprint that actually has pixels. Sentinel-2 publishes its complement as NODATA_PIXEL_PERCENTAGE, and merged catalogues put both in this column, so 8 and 92 describe the same scene. Unit: %.",
      },
      {
        name: "collection_category",
        type: "string",
        values: ["T1","T2","RT"],
        note: "RT is real-time and gets replaced within days. Nothing else in the row says it is provisional.",
      },
    ],
    apt: ["antimeridian","wrong-bbox","duplicates","wrong-winding","awkward-keys"],
  },
  {
    id: "elevation-contours",
    label: "Elevation contours & spot heights",
    family: "earth",
    blurb: "Contours and spot heights vectorised from DEM tiles. Heights are feet on one tile and metres on the next with no unit column, so a profile tool draws a 3× cliff at the join.",
    geometry: "track",
    fields: [
      {
        name: "objectid",
        type: "int",
        example: "184203",
        min: 1,
        max: 900000,
        note: "Unique per tile, not per mosaic. Merge two tiles and the ids collide.",
      },
      {
        name: "elevation",
        type: "float",
        example: "1250",
        min: -20,
        max: 1450,
        note: "Feet on 7.5-minute quad tiles, metres on 3DEP-derived tiles, and no unit column anywhere. -9999 lands here wherever the DEM had no data. Unit: m or ft, unmarked.",
      },
      {
        name: "contour_type",
        type: "string",
        values: ["index","intermediate","supplementary","depression","approximate"],
        note: "'approximate' contours are drawn where the source was unreliable and carry the same elevation field as the rest, so nothing downstream weights them differently.",
      },
      {
        name: "contour_interval",
        type: "int",
        example: "10",
        min: 5,
        max: 20,
        nullable: true,
        note: "In whatever unit elevation is in, which is not recorded. A 10 next to a 5 is the same interval on two tiles. Unit: same as elevation.",
      },
      {
        name: "depression",
        type: "string",
        values: ["Y","N","T","F","1","0",""],
        note: "The hachure flag, as a one-character string because DBF has no boolean. 'F', '0' and '' all mean no, and all three are truthy in most importers.",
      },
      {
        name: "vertical_datum",
        type: "string",
        values: ["NAVD88","NGVD29","EGM96","EGM2008","ODN","MSL"],
        nullable: true,
        note: "Empty on roughly a third of rows. NGVD29 and NAVD88 differ by up to a metre, and by different amounts in different places.",
      },
      {
        name: "horizontal_datum",
        type: "string",
        values: ["NAD83","WGS84","ETRS89","NAD27"],
        note: "NAD27 rows sit a few tens of metres off WGS84 and nothing reprojects them, because the coordinates already look like degrees.",
      },
      {
        name: "source_dem",
        type: "string",
        values: ["USGS_3DEP_1m_MA_CentralEastern_2021","USGS_NED_1/3_arcsec","OS_Terrain_5_DTM_2019","COP30_2021_v1","SRTM_v3_1arcsec"],
        note: "The only place the resolution and the vintage of the underlying model appear, as free text with a slash in one value that splits a CSV column.",
      },
      {
        name: "dem_resolution",
        type: "int",
        example: "1",
        min: 1,
        max: 10,
        note: "The DEM's post spacing, not the contour's accuracy. A 1 m DEM smoothed before vectorising gives contours no better than a 10 m one. Unit: m.",
      },
      {
        name: "spot_height_class",
        type: "string",
        values: ["summit","saddle","pass","benchmark","trig_point","pit","water_level"],
        nullable: true,
        note: "Point rows only, blank on every contour. A water_level height is the water surface, not the bed, and gets read as terrain.",
      },
      {
        name: "vertical_accuracy_rmse",
        type: "float",
        example: "0.19",
        min: 0.04,
        max: 2.5,
        nullable: true,
        note: "RMSEz, in metres from federal deliveries and centimetres from survey contractors, in the same column. Shapefile truncates the name to VERTICAL_A. Unit: m or cm.",
      },
      {
        name: "collect_date",
        type: "iso-datetime",
        example: "2019-11-04T00:00:00Z",
        nullable: true,
        note: "The flight date, not the vectorisation date. Contours from a 2019 flight ship in 2024 with a 2024 date in the metadata elsewhere, and the DBF form keeps no time at all.",
      },
      {
        name: "tile_name",
        type: "string",
        values: ["N51W002","N51W003","N52W002","N38W078","N47W122","N34W118"],
        note: "The DEM tile the line was cut from. One real contour is several features differing only here — until the elevations stop agreeing across the seam.",
      },
    ],
    apt: ["zm-coords","vertex-bomb","precision-drift","degenerate","duplicates"],
  },
  {
    id: "weather-observations",
    label: "Weather observations & forecasts",
    family: "earth",
    blurb: "Station observations, wind vectors and forecast zones. One temperature column in Celsius, Fahrenheit and Kelvin, and a wind direction that is 'from' on some rows and 'to' on others.",
    geometry: "scatter",
    fields: [
      {
        name: "station_id",
        type: "string",
        values: ["EGLL","KJFK","LFPG","EDDF","723650","947680","AT123","46042"],
        note: "ICAO for airports, a numeric mesonet or buoy id for everything else, and both in one column. 'EGLL' and '723650' key against different tables.",
      },
      {
        name: "wmo_id",
        type: "int",
        example: "3772",
        min: 1001,
        max: 99999,
        nullable: true,
        note: "The real identifier is '03772' — block number then station. Stored as an integer the leading zero is gone and it joins to nothing.",
      },
      {
        name: "obs_time",
        type: "iso-datetime",
        example: "2024-11-03T02:50:00Z",
        note: "Observation time on station rows and the model run time on anything derived from a forecast. Nothing in the row distinguishes them.",
      },
      {
        name: "valid_time",
        type: "iso-datetime",
        example: "2024-11-06T12:00:00Z",
        nullable: true,
        note: "Forecast rows only: the hour being described. Blank on observations, so a single time column built from both means nothing.",
      },
      {
        name: "report_type",
        type: "string",
        values: ["METAR","SPECI","SYNOP","BUOY","MESONET","RADAR","MOS"],
        note: "SPECI is an off-schedule report issued because conditions changed. Take the hourly mean over the column and it is weighted towards bad weather.",
      },
      {
        name: "air_temp",
        type: "float",
        example: "18.3",
        min: -25,
        max: 42,
        note: "Celsius from METAR, Fahrenheit from US mesonets, Kelvin from model output. 18, 64 and 291 are the same afternoon. Unit: °C, °F or K.",
      },
      {
        name: "dew_point",
        type: "float",
        example: "11.2",
        min: -30,
        max: 25,
        nullable: true,
        note: "Converted with air_temp on a good day and left in the source unit on a bad one, which is how a dew point ends up above the temperature. Unit: same as air_temp.",
      },
      {
        name: "wind_dir_deg",
        type: "int",
        example: "270",
        min: 0,
        max: 360,
        nullable: true,
        note: "The direction the wind comes from, except on model-derived rows where it is the direction it goes. 0 means calm and 360 means due north, and 'VRB' arrives here from the raw METAR. Unit: degrees.",
      },
      {
        name: "wind_speed",
        type: "float",
        example: "11",
        min: 0,
        max: 45,
        note: "Knots in aviation feeds, metres per second in SYNOP, km/h in national portals. Nothing in the file says which. Unit: kt, m·s⁻¹ or km·h⁻¹.",
      },
      {
        name: "mslp_hpa",
        type: "float",
        example: "1012.4",
        min: 975,
        max: 1035,
        nullable: true,
        note: "Some feeds ship tenths of a hectopascal as an integer, so 10124 sits in the same column as 1012.4. Unit: hPa.",
      },
      {
        name: "visibility",
        type: "float",
        example: "9999",
        min: 50,
        max: 9999,
        note: "Metres, where 9999 means 10 km or more rather than 9,999 m. US rows put statute miles in the same column, so 10 is either fine or fog. Unit: m or statute miles.",
      },
      {
        name: "precip_accum_1hr",
        type: "float",
        example: "0.2",
        min: 0,
        max: 12,
        nullable: true,
        note: "Millimetres or inches, and a trace is written -0.01, 0.001 or 'T' depending on the source. Unit: mm or in.",
      },
      {
        name: "reflectivity_dbz",
        type: "float",
        example: "42.5",
        min: -32,
        max: 70,
        nullable: true,
        note: "Radar cell rows only. Values near -32 are the no-echo fill, not drizzle, and a colour ramp built off the column minimum starts there. Unit: dBZ.",
      },
      {
        name: "qc_flag",
        type: "string",
        values: ["V","S","X","Z","C","Q",""],
        note: "X is 'rejected' and Z is 'never checked'. The rejected rows ship anyway with the impossible value still in the measurement column.",
      },
    ],
    apt: ["date-chaos","coincident","sparse-global","unstable-types","null-empties"],
  },
  {
    id: "land-cover-ndvi",
    label: "Land cover & vegetation indices",
    family: "earth",
    blurb: "Class polygons and zonal NDVI statistics. NDVI is -1..1 on one row and 0..10000 on the next, and the class code is a text key that every spreadsheet turns into a number.",
    geometry: "zone",
    fields: [
      {
        name: "class_code",
        type: "string",
        values: ["112","121","211","231","243","311","312","313","324","411","512"],
        note: "Hierarchical: '312' is a child of '31', which is a child of '3'. Text because the legend is text, and the real column is CODE_12 in one vintage and CODE_18 in the next, so a pipeline written for one finds nothing in the other.",
      },
      {
        name: "class_name",
        type: "string",
        values: ["Discontinuous urban fabric","Industrial or commercial units","Non-irrigated arable land","Pastures","Broad-leaved forest","Coniferous forest","Mixed forest","Transitional woodland-shrub","Peat bogs","Water bodies"],
        note: "Free text from the legend document, not a controlled list. 'Broad-leaved forest' and 'Broadleaved forest' both occur in one national delivery, and the hyphen is the only difference.",
      },
      {
        name: "class_level",
        type: "int",
        example: "3",
        min: 1,
        max: 3,
        note: "Which level of the hierarchy class_code sits at. Rows at different levels overlap in area, so summing area by class double-counts.",
      },
      {
        name: "legend_version",
        type: "string",
        values: ["CLC2012","CLC2018","NLCD2011","NLCD2019","CGLS100"],
        nullable: true,
        note: "Codes were reused between vintages with new meanings. Without this field a 1992 and a 2019 polygon that both say 21 disagree about what 21 is.",
      },
      {
        name: "ndvi_mean",
        type: "float",
        example: "0.62",
        min: -0.2,
        max: 0.92,
        nullable: true,
        note: "The -1..1 index, except where the int16 storage form went out with the 0.0001 scale factor unapplied, and -3000 where the MODIS fill pixels were averaged in with the rest.",
      },
      {
        name: "ndvi_stddev",
        type: "float",
        example: "0.08",
        min: 0.01,
        max: 0.35,
        nullable: true,
        note: "Scaled the same way as ndvi_mean on some rows and not on others, so the ratio between the two columns changes by 10,000× down the file.",
      },
      {
        name: "composite_end",
        type: "iso-datetime",
        example: "2024-07-31T00:00:00Z",
        note: "The end of a 16-day composite, not an acquisition. Every pixel inside the polygon is from a different day within that window, and the good ones are biased towards the cloud-free days.",
      },
      {
        name: "crop_code",
        type: "string",
        values: ["1","5","24","36","61","176","190"],
        note: "CDL codes as strings that look like numbers. 176 is 'Grassland/Pasture' and 61 is 'Fallow/Idle Cropland' — neither is a crop, and both get counted as one.",
      },
      {
        name: "tree_cover_pct",
        type: "int",
        example: "78",
        min: 0,
        max: 100,
        nullable: true,
        note: "Canopy cover in the baseline year 2000, not now. A polygon flagged as cleared still reads 78. Unit: %.",
      },
      {
        name: "change_type",
        type: "string",
        values: ["deforestation","regrowth","urban_expansion","no_change","burn_scar"],
        nullable: true,
        note: "Blank means 'not assessed', not 'no change' — and 'no_change' is also a value, so the two are distinguishable only if you notice.",
      },
      {
        name: "alert_date",
        type: "int",
        example: "3287",
        min: 1200,
        max: 3600,
        note: "The GLAD alert convention. Read as a year it is nonsense; read as epoch seconds it lands in January 1970. Unit: days since 2014-12-31.",
      },
      {
        name: "area_ha",
        type: "float",
        example: "412.7",
        min: 5,
        max: 4000,
        note: "Computed in the source equal-area projection before the polygon was clipped to the tile. It does not match the geometry in the file, and the report totals this column. Unit: ha.",
      },
      {
        name: "pixel_count",
        type: "int",
        example: "6612",
        min: 40,
        max: 400000,
        note: "The zonal-statistics cell count, not an area. MOD13Q1 rows count 250 m pixels and PSScene rows count 3 m ones, so summing the column across the layer means nothing.",
      },
      {
        name: "source_sensor",
        type: "string",
        values: ["S2A","S2B","LC08","LC09","MOD13Q1","PSScene"],
        note: "A platform id, a MODIS product short name and a Planet item type in one column. The MOD13Q1 boundaries were drawn at 250 m and the PSScene ones at 3 m, in the same layer.",
      },
    ],
    apt: ["holes","vertex-bomb","self-intersecting","wrong-winding","degenerate"],
  },
  {
    id: "natural-hazard-zones",
    label: "Natural hazard zones",
    family: "earth",
    blurb: "Flood zones, fault traces and fire perimeters stacked into one table. The zone code is an unordered string, a hole means 'not assessed' rather than safe, and each perimeter timestep still contains the one before it.",
    geometry: "zone",
    fields: [
      {
        name: "hazard_type",
        type: "string",
        values: ["flood","seismic_fault","wildfire","landslide","tsunami"],
        note: "Decides which of the other columns are populated, and nothing enforces it. A wildfire row carrying a flood zone code exists because the layers were merged on a common schema.",
      },
      {
        name: "fld_zone",
        type: "string",
        values: ["A","AE","AH","AO","A99","AR","V","VE","X","D"],
        nullable: true,
        note: "Ordinal risk as an unordered string. Sorted alphabetically, 'X' (minimal) lands last and 'A99' sits between 'A' and 'AE'.",
      },
      {
        name: "zone_subtype",
        type: "string",
        values: ["0.2 PCT ANNUAL CHANCE FLOOD HAZARD","FLOODWAY","AREA OF MINIMAL FLOOD HAZARD","AREA WITH REDUCED FLOOD RISK DUE TO LEVEE","RIVERINE FLOODWAY SHOWN IN COASTAL ZONE","AREA OF UNDETERMINED FLOOD HAZARD"],
        nullable: true,
        note: "The severity the code omits, in free text with a percent sign and a full stop in it. This is what separates the 100-year zone from the 500-year one, and it is the field a symbology rule never reads.",
      },
      {
        name: "static_bfe",
        type: "float",
        example: "18.4",
        min: 2,
        max: 60,
        nullable: true,
        note: "Base flood elevation in feet, and -9999 wherever one was never computed. A legend stretched over the column minimum starts at -9999. Unit: ft NAVD88.",
      },
      {
        name: "sfha_tf",
        type: "string",
        values: ["T","F"],
        note: "Special flood hazard area as a one-character string, because DBF has no boolean. 'F' is truthy in every language that reads this file.",
      },
      {
        name: "depth_ft",
        type: "int",
        example: "2",
        min: 1,
        max: 3,
        nullable: true,
        note: "Shallow-flooding (AO) zones only. Blank elsewhere, which reads as zero depth rather than 'not that kind of zone'. Unit: ft.",
      },
      {
        name: "incident_name",
        type: "string",
        values: ["Dixie Fire","Caldor Fire","Bootleg Fire","Cedar Creek Fire","Marshall Fire","August Complex","Hermits Peak/Calf Canyon"],
        nullable: true,
        note: "Neither unique nor stable — renamed when two fires merge, reused in later years, and one of them has a slash in it. It is still what most people group by.",
      },
      {
        name: "perimeter_datetime",
        type: "iso-datetime",
        example: "2021-08-05T18:30:00Z",
        nullable: true,
        note: "The operational period this ring was mapped in. Several rows differ only here, and the later ones contain the earlier ones.",
      },
      {
        name: "gis_acres",
        type: "float",
        example: "963309",
        min: 120,
        max: 400000,
        nullable: true,
        note: "Often carried over from the previous perimeter, so it describes yesterday's ring — in acres, in an Albers projection nobody recorded. Unit: acres.",
      },
      {
        name: "containment_pct",
        type: "int",
        example: "42",
        min: 0,
        max: 100,
        nullable: true,
        note: "Containment of the incident, not of this polygon. Every timestep of one fire eventually reads 100. Unit: %.",
      },
      {
        name: "irwin_id",
        type: "string",
        values: ["6f4d1a2c-8b7e-4a91-9f3d-2c5e8a1b7d40","{6F4D1A2C-8B7E-4A91-9F3D-2C5E8A1B7D40}","b1c07f55-2d3a-4e18-8a6b-90f2c4d71e33","{B1C07F55-2D3A-4E18-8A6B-90F2C4D71E33}","e93a5c10-7f42-4bd6-a018-5c73e2f9a441"],
        nullable: true,
        note: "The UUID that should key the incident. Brace-wrapped and uppercase in one layer, bare and lowercase in the next, so the join between the point and polygon layers matches nothing. Blank on historical rows.",
      },
      {
        name: "fault_name",
        type: "string",
        values: ["Hayward fault zone, southeast extension","San Andreas fault zone, Peninsula section","Wasatch fault zone, Salt Lake City section","Rodgers Creek fault zone, northern section","Calaveras fault zone, central section"],
        nullable: true,
        note: "Includes the section qualifier after a comma, so an unquoted CSV round-trip splits one fault across two columns and shifts every field after it.",
      },
      {
        name: "slip_rate",
        type: "string",
        values: ["Less than 0.2 mm/yr","Between 0.2 and 1.0 mm/yr","Between 1.0 and 5.0 mm/yr","Greater than 5.0 mm/yr","Unspecified"],
        nullable: true,
        note: "A category, not a number — that is how the USGS publishes it. Every numeric slip-rate column downstream was flattened from this by someone who took the lower bound on some rows and the midpoint on others.",
      },
      {
        name: "fault_certainty",
        type: "string",
        values: ["accurate","approximate","inferred","concealed","queried"],
        nullable: true,
        note: "'concealed' and 'inferred' traces are drawn with the same weight as mapped ones. The values contain no separator a styling rule can key on, so all five render identically.",
      },
    ],
    apt: ["holes","mixed-geometry","id-chaos","duplicates","null-empties"],
  },
];
