import type { DataProfile } from "./index";

/**
 * Official statistics, and the geography they are pinned to.
 *
 * Suppression is the family trait: a count too small to publish becomes
 * -666666666 or -999999 or an asterisk, and it is still a number in a numeric
 * column. Everything else follows from aggregating people to a polygon they
 * were never in.
 */
export const PUBLIC_PROFILES: DataProfile[] = [
  {
    id: "census-boundary",
    label: "Census & boundary",
    family: "public",
    blurb: "Tract polygons with ACS estimates joined on: the GEOID loses its leading zero the first time anything reads it as a number, and the -666666666 suppression code stretches the colour ramp until every tract is one shade.",
    geometry: "zone",
    fields: [
      {
        name: "GEOID",
        type: "string",
        example: "06075012402",
        note: "State, county and tract concatenated: 06 + 075 + 012402. It is a string — the leading zero goes the moment eleven digits reach a spreadsheet or a dtype-guessing reader, and the join to the geometry then matches nothing. Compose it from STATEFP, COUNTYFP and TRACTCE rather than drawing it, or the three columns disagree with the key they are supposed to make.",
      },
      {
        name: "AFFGEOID",
        type: "string",
        example: "1400000US06075012402",
        note: "The ACS API's own geography id: summary level 1400000, a literal US, then the GEOID. That prefix is constant on every row and is not a pattern to be randomised. Joined straight to GEOID it matches nothing until someone splits on US, and it is the one identifier here that survives a numeric cast intact.",
      },
      {
        name: "STATEFP",
        type: "string",
        values: ["01","02","06","09","12","17","36","46","48","72"],
        note: "Two characters, always zero-padded. 6 and \"06\" are not the same key and only one of them is in the shapefile. 72 is Puerto Rico, so a bbox drawn round the data is not the contiguous US.",
      },
      {
        name: "COUNTYFP",
        type: "string",
        example: "075",
        note: "Three characters, unique only within the state: county 001 exists in nearly every one of them. The codes are odd numbers by original design, so an even one is a later addition or a typo, and joining county without state silently fans out.",
      },
      {
        name: "TRACTCE",
        type: "string",
        example: "012402",
        note: "Six characters with two implied decimal places: 012402 is tract 124.02, not tract 12,402. Sorting it as a number reorders the whole county, and the 9900 series is water rather than land.",
      },
      {
        name: "NAMELSAD",
        type: "string",
        literal: true,
        example: "Census Tract 124.02",
        note: "The same tract number as TRACTCE in a different notation, so joining on the label matches nothing, and it is not unique — every county has a Census Tract 1. Compose it from TRACTCE with the implied decimal put back; the \"Census Tract \" prefix is a literal, not a shape to randomise.",
      },
      {
        name: "ALAND",
        type: "int",
        example: "2417832",
        min: 120000,
        max: 60000000,
        note: "Square metres, not acres and not square miles — big enough that people assume feet and divide by 43,560. It is 0 on water-only tracts, which is a divide-by-zero in every population-density calculation ever written against this file. Unit: square metres.",
      },
      {
        name: "AWATER",
        type: "int",
        example: "180452",
        min: 0,
        max: 5000000,
        note: "Square metres of water, and 0 on most inland tracts. A tract can be entirely water and still report residents living on moorings, so ALAND + AWATER is the only area figure that behaves. Unit: square metres.",
      },
      {
        name: "INTPTLAT",
        type: "string",
        example: "+37.7576792",
        note: "A string with an explicit leading plus sign: strict readers keep the sign as text and the column never becomes numeric. Latitude first, sitting beside geometry that is longitude first. Write it from the feature's own position at seven decimals, or the label points at another state.",
      },
      {
        name: "INTPTLON",
        type: "string",
        example: "-122.4193286",
        note: "The paired ordinate, published second. It is an interior point chosen to fall inside the polygon, not the centroid — labelling it the centroid moves a horseshoe-shaped tract's marker into its neighbour.",
      },
      {
        name: "B01003_001E",
        type: "int",
        example: "4218",
        min: 800,
        max: 8200,
        nullable: true,
        note: "Total population, estimate. Tracts are drawn to hold about 4,000 people, so 40,000 is a merged geography and 12 is a marina or a prison. Suppressed cells arrive as -666666666, which is a number, so it charts, sums and sets the bottom of the legend.",
      },
      {
        name: "B01003_001M",
        type: "int",
        example: "612",
        min: 12,
        max: 900,
        nullable: true,
        note: "The margin of error on the estimate to its left, same units, at 90% confidence rather than 95%. -555555555 means the estimate was controlled and no margin applies. Drop this column and a tract of 42 ± 61 people drives the map.",
      },
      {
        name: "B19013_001E",
        type: "int",
        example: "98750",
        min: 14500,
        max: 250001,
        nullable: true,
        note: "Median household income, top- and bottom-coded: 250001 means \"at least that\" and 2499 means \"at most that\", and neither is a measurement. Medians also do not aggregate — averaging this column across tracts is meaningless, and it is done constantly. Unit: USD.",
      },
      {
        name: "S1701_C03_001E",
        type: "float",
        example: "18.4",
        min: 1.4,
        max: 58,
        nullable: true,
        note: "Percent below the poverty level: 0-100 in the ACS tables and 0-1 in the modelled products people merge beside them. Its denominator is the population poverty status was determined for, not the total population, so it never reconciles with B01003_001E. Unit: percent.",
      },
    ],
    apt: ["holes","vertex-bomb","unclosed-rings","wrong-winding","precision-drift","awkward-keys","null-empties"],
  },
  {
    id: "health-epidemiology",
    label: "Health & epidemiology",
    family: "public",
    blurb: "Hospital capacity rows and county case counts in one layer: -999999 in the bed columns means \"between one and three, redacted\", and the cases carry the reporting hospital's coordinates rather than anywhere a patient lives.",
    geometry: "scatter",
    fields: [
      {
        name: "ccn",
        type: "string",
        example: "050308",
        note: "CMS Certification Number: six characters, zero-padded, and the first two encode the state, so it looks like an integer and is not one. Reissued when a facility changes ownership, which makes it unstable across years as well as untyped. Keep its first two digits in step with fips_code.",
      },
      {
        name: "hospital_name",
        type: "string",
        values: ["ST MARYS REGIONAL MEDICAL CENTER","St. Mary's Regional Medical Center","SAINT MARYS REGIONAL MED CTR","MERCY GENERAL HOSPITAL","Mercy General Hosp","COUNTY MEMORIAL HOSPITAL","UNIVERSITY MEDICAL CENTER","VALLEY COMMUNITY HOSPITAL","LAKESIDE BEHAVIORAL HEALTH","BAYSIDE CRITICAL ACCESS HOSP"],
        note: "Free text, abbreviated differently every submission quarter, and the only usable join key on rows where ccn is blank. The first three values are one hospital, and any group-by treats them as three.",
      },
      {
        name: "hospital_subtype",
        type: "string",
        values: ["Short Term","Critical Access Hospitals","Childrens Hospitals","Long Term","Psychiatric","Rehabilitation"],
        note: "The HHS vocabulary verbatim — mixed singular and plural, and no apostrophe in Childrens. A site reports one subtype this week and another the next, so counts move between categories without moving on the map.",
      },
      {
        name: "fips_code",
        type: "string",
        example: "06075",
        nullable: true,
        note: "Five characters, state plus county. A feed that drops the leading zero turns 06075 into 6075, which matches nothing, and it is blank on rows aggregated statewide and on facilities whose address never geocoded.",
      },
      {
        name: "collection_week",
        type: "iso-datetime",
        example: "2022-01-07T00:00:00",
        note: "The Friday that starts a seven-day window. Some vintages stamp the window's last day instead, so joining two extracts shifts every count by exactly one week and nothing in the file says which is which. No offset: it is a date pretending to be an instant.",
      },
      {
        name: "onset_dt",
        type: "iso-datetime",
        example: "2022-01-03T00:00:00",
        nullable: true,
        note: "When the person became ill. Blank on most rows, and where it is blank the report date is copied in, which slides the whole epidemic curve about a week to the right.",
      },
      {
        name: "cdc_report_dt",
        type: "iso-datetime",
        example: "2022-01-10T00:00:00",
        note: "When the case reached the health department. Weekend cases pile onto Monday — a reporting artefact that renders as a weekly wave in anything animated by this column.",
      },
      {
        name: "icd10_code",
        type: "string",
        values: ["U07.1","J09.X2","J10.1","J11.1","A08.0","A09","B34.9","J18.9"],
        nullable: true,
        note: "ICD-10 on recent rows and ICD-9 on the historical ones: U07.1 and 480.9 sit in the same column meaning nearly the same thing, and neither code list ships with the file. The dot is part of the code in some exports and stripped in others.",
      },
      {
        name: "new_case",
        type: "int",
        example: "37",
        min: 0,
        max: 480,
        note: "The week's new cases — singular, because that is what CDC named it, next to a plural cumulative column. It goes negative when a backfill removes duplicates or moves a case to another county: a cumulative sum is still right, a bar chart has bars below the axis.",
      },
      {
        name: "tot_cases",
        type: "int",
        example: "18422",
        min: 0,
        max: 190000,
        note: "The running total to date, in the same table as the weekly figure and folding confirmed and probable together. Summing it across rows produces a number in the billions, and someone does it every week.",
      },
      {
        name: "crude_rate",
        type: "float",
        example: "412.7",
        min: 12,
        max: 6200,
        nullable: true,
        note: "Crude, not age-adjusted, and shown beside age-adjusted figures in the same dashboard, so a county full of retirees always looks like an outbreak. Recomputing tot_cases ÷ population × 100,000 does not reproduce it, because the denominator is a different vintage. Unit: cases per 100,000.",
      },
      {
        name: "population",
        type: "int",
        example: "184300",
        min: 2500,
        max: 350000,
        nullable: true,
        note: "The denominator behind the rate, a vintage or two older than the geometry it is attached to. Blank on facility rows, where there is no population to speak of, and summed across overlapping catchments it exceeds the region it covers. Unit: people.",
      },
      {
        name: "inpatient_beds_used_7_day_avg",
        type: "float",
        example: "212.4",
        min: 0,
        max: 420,
        nullable: true,
        note: "A seven-day average, and -999999 wherever the true value is between one and three. Truncated to ten characters for a DBF it becomes inpatient_, which is also what the field below becomes — one of them silently wins. Unit: beds.",
      },
      {
        name: "inpatient_beds_used_7_day_sum",
        type: "float",
        example: "1486.8",
        min: 0,
        max: 2940,
        nullable: true,
        note: "The same week's total, seven times the average beside it under a name that first differs at character 27. Derive it as 7 × the average so the pair is consistent before a problem pulls it apart; charted on one axis, the average looks like a collapse. Unit: beds.",
      },
    ],
    apt: ["coincident","duplicates","date-chaos","null-empties","unstable-types","awkward-keys"],
  },
  {
    id: "crime-incident",
    label: "Crime & incident",
    family: "public",
    blurb: "Offence reports geocoded to the hundred-block midpoint: sixty incidents share one coordinate, unknown times default to midnight on the 1st, and the column called date is the offence rather than the report.",
    geometry: "scatter",
    fields: [
      {
        name: "case_number",
        type: "string",
        example: "JB247190",
        note: "The records-management number: a year-letter prefix and a near-sequential body. Reissued when a case is reclassified and repeated across every offence of one incident, so it is not a primary key however much it looks like one.",
      },
      {
        name: "date",
        type: "iso-datetime",
        example: "2024-03-07T21:15:00",
        note: "Named date, holds a time, and it is when the offence happened rather than when it was reported. Local wall-clock with no offset, so one hour repeats every autumn and one is missing every spring, and everything nobody knew sits at 00:00:00 on the 1st.",
      },
      {
        name: "updated_on",
        type: "iso-datetime",
        example: "2024-03-14T15:42:00",
        note: "When the row last changed, which half the dashboards in existence chart and label the report date. It moves years after the fact when a case is reclassified, so yesterday's extract and today's disagree on rows nobody touched.",
      },
      {
        name: "block",
        type: "string",
        values: ["0000X N STATE ST","047XX S ASHLAND AVE","008XX W BELMONT AVE","063XX S DR MARTIN LUTHER KING JR DR","0000X W JACKSON BLVD","035XX N SHEFFIELD AVE","011XX E 79TH ST","024XX W DEVON AVE","0000X E RANDOLPH ST","091XX S COTTAGE GROVE AVE"],
        nullable: true,
        note: "The address already redacted to the hundred block: 0000X means somewhere between 1 and 99. The coordinates are that block's midpoint, so the pin is a summary and not a location, and dozens of rows share both the string and the point.",
      },
      {
        name: "iucr",
        type: "string",
        values: ["0110","0313","031A","0320","0460","0486","0497","0560","0610","0810","0820","0890","0910","1153","1310","1320","1811","2024"],
        note: "Four characters with a leading zero, and some of them end in a letter: 031A is not a number and 0486 is not 486. Retired codes stay in the historical rows forever. Draw this first and derive primary_type, description and fbi_code from it, or the clean file disagrees with itself before any problem is applied.",
      },
      {
        name: "primary_type",
        type: "string",
        values: ["THEFT","BATTERY","CRIMINAL DAMAGE","ASSAULT","BURGLARY","NARCOTICS","MOTOR VEHICLE THEFT","ROBBERY","DECEPTIVE PRACTICE","WEAPONS VIOLATION","OTHER OFFENSE","NON-CRIMINAL","NON - CRIMINAL"],
        note: "Upper case with embedded spaces, derived from iucr at export time rather than stored beside it, so where the code drifted the label did not follow. NON-CRIMINAL and NON - CRIMINAL are the same category and group as two.",
      },
      {
        name: "description",
        type: "string",
        values: ["DOMESTIC BATTERY SIMPLE","SIMPLE","OVER $500","$500 AND UNDER","FORCIBLE ENTRY","UNLAWFUL ENTRY","TO VEHICLE","POSS: CANNABIS 30GMS OR LESS","AUTOMOBILE","FROM BUILDING","ARMED: HANDGUN"],
        note: "The secondary description, meaningless on its own: SIMPLE and OVER $500 need the primary type beside them to mean anything, and it carries currency symbols and colons into every CSV and popup.",
      },
      {
        name: "location_description",
        type: "string",
        values: ["STREET","RESIDENCE","APARTMENT","SIDEWALK","PARKING LOT / GARAGE (NON RESIDENTIAL)","PARKING LOT/GARAGE(NON.RESID.)","SMALL RETAIL STORE","ALLEY","SCHOOL, PUBLIC, BUILDING","RESIDENCE - GARAGE","OTHER"],
        nullable: true,
        note: "A controlled list that quietly gained and lost values every year. The two parking-lot spellings are one category and grouping by this column splits it in two, and the commas inside the values are a problem for every unquoted export.",
      },
      {
        name: "arrest",
        type: "bool",
        example: "false",
        note: "true/false in the API, the strings \"true\"/\"false\" in the CSV, and Y/N in half the extracts derived from it. \"N\" is truthy in every language anyone will load this with.",
      },
      {
        name: "beat",
        type: "string",
        example: "0334",
        note: "The patrol beat: four characters with a leading zero, and its first two are the district, so beat 0334 belongs to district 003. Nothing enforces that, and rows kept across a redistricting say otherwise.",
      },
      {
        name: "district",
        type: "string",
        example: "003",
        note: "Three characters, zero-padded, and 031 is the code for outside the city or unknown rather than a real district. Read as a number it is indistinguishable from the ward and community-area codes in the same row.",
      },
      {
        name: "fbi_code",
        type: "string",
        example: "08B",
        note: "The UCR classification: a parallel scheme that does not map one-to-one onto iucr and is revised on a different schedule, so the two disagree on a meaningful share of rows. The letter makes it the one code here that survives a numeric cast.",
      },
      {
        name: "x_coordinate",
        type: "float",
        example: "1176312.5",
        min: 1092000,
        max: 1205000,
        nullable: true,
        note: "State Plane Illinois East in US survey feet, published beside latitude and longitude and blank on exactly the rows where those are blank. 1,176,312 is not a longitude, and a generic x/y importer will use it as one. Unit: US survey feet (EPSG:3435).",
      },
      {
        name: "y_coordinate",
        type: "float",
        example: "1901743.2",
        min: 1813000,
        max: 1951000,
        nullable: true,
        note: "The northing half of the pair, rounded to a tenth of a foot — about 3 cm — on data whose real accuracy is the width of a city block. Derive both from the feature's own position, or the projected pair describes a different city from the geometry. Unit: US survey feet (EPSG:3435).",
      },
    ],
    apt: ["null-island","coincident","dense-cluster","date-chaos","duplicates","id-chaos"],
  },
];
