"use client";

import { useEffect, useState } from "react";
import { Button, Card, CardTitle } from "./ui";
import { formatBytes } from "@/lib/download";
import type { GeneratedFile } from "@/lib/types";

/** The context is built once as structure, then rendered and copied from the
 *  same source — so what is on screen is exactly what lands on the clipboard. */
interface ContextBlock {
  intro: string;
  fields: Array<[string, string]>;
  heading: string;
  problems: string[];
}

function buildContext(file: GeneratedFile, formatLabel: string): ContextBlock {
  const fields: Array<[string, string]> = [
    ["File", file.filename],
    ["Format", formatLabel],
    ["Size", formatBytes(file.bytes)],
    ["Features", file.stats.features.toLocaleString()],
    ["Positions", file.map.total.toLocaleString()],
  ];

  if (file.map.bbox) {
    const [minX, minY, maxX, maxY] = file.map.bbox;
    fields.push(["Bounds", `${minX}, ${minY} to ${maxX}, ${maxY}`]);
  }
  if (file.map.outOfRange || file.map.invalid) {
    fields.push([
      "Off-world",
      `${(file.map.outOfRange + file.map.invalid).toLocaleString()} positions` +
        (file.map.invalid ? ` (${file.map.invalid.toLocaleString()} not a number)` : ""),
    ]);
  }

  return {
    intro: "This is a deliberately broken geospatial test fixture, generated by map/data.",
    fields,
    heading: "Known problems baked into this file:",
    problems: file.notes.length
      ? file.notes
      : ["None. This is a clean, well-formed file, useful as a control case."],
  };
}

function contextToText(block: ContextBlock): string {
  return [
    block.intro,
    "",
    ...block.fields.map(([label, value]) => `${label}: ${value}`),
    "",
    block.heading,
    ...block.problems.map((p) => `- ${p}`),
  ].join("\n");
}

export function OutputPanel({
  file,
  formatLabel,
}: {
  file: GeneratedFile | null;
  formatLabel: string;
}) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 1800);
    return () => clearTimeout(timer);
  }, [copied]);

  const block = file ? buildContext(file, formatLabel) : null;

  const copyContext = async () => {
    if (!block) return;
    try {
      await navigator.clipboard.writeText(contextToText(block));
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="grid gap-3 lg:grid-cols-2">
      {/* Written as a plain section rather than <Card>, so the dark tone can't
          lose a class-order fight with the card's own border and background. */}
      <section className="flex flex-col overflow-hidden rounded-[18px] bg-ink">
        <div className="flex items-start justify-between gap-3 px-4 pb-3 pt-4">
          <div className="min-w-0">
            <h2 className="text-[13px] font-semibold leading-snug tracking-tight text-white">
              Working with AI? Paste this context:
            </h2>
            <p className="mt-0.5 text-[11px] text-white/45">
              Everything wrong with this file, in one block.
            </p>
          </div>
          <Button onClick={copyContext} disabled={!block} className="shrink-0 px-3 py-1.5">
            {copied ? "Copied" : "Copy"}
          </Button>
        </div>

        <div className="scroll-thin-dark mx-4 mb-4 max-h-[268px] overflow-auto rounded-xl border border-white/10 bg-white/[0.03] p-3.5 font-mono text-[11px] leading-[1.7]">
          {block ? (
            <>
              <p className="text-white/45">{block.intro}</p>
              <dl className="mt-3">
                {block.fields.map(([label, value]) => (
                  <div key={label} className="flex gap-2">
                    <dt className="shrink-0 text-mint">{label}:</dt>
                    <dd className="min-w-0 break-words text-white/80">{value}</dd>
                  </div>
                ))}
              </dl>
              <p className="mt-3 text-mint">{block.heading}</p>
              <ul>
                {block.problems.map((problem, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="shrink-0 text-mint/45" aria-hidden>
                      -
                    </span>
                    <span className="text-white/80">{problem}</span>
                  </li>
                ))}
              </ul>
            </>
          ) : (
            <p className="text-white/35">generating…</p>
          )}
        </div>
      </section>

      <Card className="flex min-h-0 flex-col overflow-hidden p-0">
        <div className="px-4 pt-4">
          <CardTitle
            aside={
              file?.previewTruncated ? (
                <span className="font-mono text-[10px] text-dim">truncated</span>
              ) : undefined
            }
          >
            Preview
          </CardTitle>
        </div>
        <pre className="scroll-thin mt-3 max-h-[300px] overflow-auto px-4 pb-4 font-mono text-[11px] leading-relaxed text-muted">
          {file?.preview ?? ""}
        </pre>
      </Card>
    </div>
  );
}
