"use client";

import { useEffect, useState } from "react";
import { Button, Card, CardTitle } from "./ui";
import { formatBytes } from "@/lib/download";
import type { GeneratedFile } from "@/lib/types";

/**
 * Assembles the whole picture — what the file is, and every way it is
 * deliberately broken — as one block worth pasting into a chat.
 */
function buildContext(file: GeneratedFile, formatLabel: string): string {
  const lines = [
    "This is a deliberately broken geospatial test fixture, generated by map/data.",
    "",
    `File: ${file.filename}`,
    `Format: ${formatLabel}`,
    `Size: ${formatBytes(file.bytes)}`,
    `Features: ${file.stats.features.toLocaleString()}`,
    `Positions: ${file.map.total.toLocaleString()}`,
  ];

  if (file.map.bbox) {
    const [minX, minY, maxX, maxY] = file.map.bbox;
    lines.push(`Bounds: ${minX}, ${minY} to ${maxX}, ${maxY}`);
  }
  if (file.map.outOfRange || file.map.invalid) {
    lines.push(
      `Off-world positions: ${(file.map.outOfRange + file.map.invalid).toLocaleString()}` +
        (file.map.invalid ? ` (${file.map.invalid.toLocaleString()} not a number)` : ""),
    );
  }

  lines.push("", "Known problems baked into this file:");
  if (file.notes.length) {
    for (const note of file.notes) lines.push(`- ${note}`);
  } else {
    lines.push("- None. This is a clean, well-formed file, useful as a control case.");
  }
  return lines.join("\n");
}

export function OutputPanel({
  file,
  formatLabel,
}: {
  file: GeneratedFile | null;
  formatLabel: string;
}) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 1800);
    return () => clearTimeout(timer);
  }, [copied]);

  const copyContext = async () => {
    if (!file) return;
    try {
      await navigator.clipboard.writeText(buildContext(file, formatLabel));
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="grid gap-3 lg:grid-cols-2">
      <Card className="p-4">
        <div className="flex items-start justify-between gap-3">
          <h2 className="text-[13px] font-semibold leading-snug tracking-tight text-ink">
            Working with AI? Paste this context:
          </h2>
          <Button onClick={copyContext} disabled={!file} className="shrink-0 px-3 py-1.5">
            {copied ? "Copied" : "Copy"}
          </Button>
        </div>

        {file?.notes.length ? (
          <ul className="mt-3 space-y-2">
            {file.notes.map((note, i) => (
              <li key={i} className="flex gap-2.5 text-[12px] leading-snug text-muted">
                <span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-line-strong" aria-hidden />
                <span>{note}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-3 text-[12px] leading-snug text-dim">
            Nothing selected — this is a clean, well-formed file. Useful as the control case.
          </p>
        )}
      </Card>

      <Card className="flex min-h-0 flex-col overflow-hidden p-0">
        <div className="px-4 pt-4">
          <CardTitle
            aside={
              file?.previewTruncated ? (
                <span className="font-mono text-[10px] text-dim">truncated</span>
              ) : undefined
            }
          >
            Preview
          </CardTitle>
        </div>
        <pre className="scroll-thin mt-3 max-h-[300px] overflow-auto px-4 pb-4 font-mono text-[11px] leading-relaxed text-muted">
          {file?.preview ?? ""}
        </pre>
      </Card>
    </div>
  );
}
