import type { DataProfile } from "./index";

/**
 * Where people were, where businesses are, and what the two are worth.
 *
 * The family trait here is precision that is claimed rather than held: a
 * coordinate rounded for privacy but still shipped beside an accuracy in
 * metres, a venue polygon that is the building next door, a catchment drawn by
 * a model that never saw a road.
 */
export const ADTECH_PROFILES: DataProfile[] = [
  {
    id: "mobile-location-pings",
    label: "Mobile Location Data",
    family: "adtech",
    blurb: "Coordinates truncated to 2 dp by the exchange still carry a horizontal_accuracy of 8 metres, so a city's pings land on a 1.1 km lattice that every dwell algorithm reads as one enormous venue.",
    geometry: "scatter",
    fields: [
      {
        name: "ad_id",
        type: "string",
        values: ["6D92078A-8246-4BA4-AE5B-76104861E7DC","0F3C4E11-9B77-4A2D-8C61-5D0E2A7F41B9","B7A1D0C4-2E58-4F36-9A0B-1C8E7D45F203","4E8B12FA-6C39-4D71-B25E-90A3C6F8D147","c1f8a2d4-5b60-4e93-8a17-2d6f0b93c845","9a2e7c31-08d5-4b6f-a913-7ce4d25f0b68","3d5f8b02-71a4-4c98-b0e2-6f19a8d3c740","e0b64a97-3f21-4d85-9c60-8a72e5104bd3"],
        note: "IDFAs arrive upper case and AAIDs lower case, so a case-sensitive join counts one device twice and a case-insensitive one merges two. The all-zero UUID is a third shape in the same column and it is not a device at all.",
      },
      {
        name: "id_type",
        type: "string",
        values: ["idfa","aaid","gaid","idfv",""],
        nullable: true,
        note: "Some partners call the Android identifier aaid and some call it gaid. Counting distinct id types gives you more platforms than exist, and idfv is per-vendor so it never joins to anything.",
      },
      {
        name: "lmt",
        type: "int",
        example: "0",
        min: 0,
        max: 1,
        note: "OpenRTB's limit-ad-tracking flag. It is 0/1 here, true/false out of the SDK adapter and empty from the exchange, so a filter written as lmt = 0 keeps every row the exchange sent.",
      },
      {
        name: "utc_timestamp",
        type: "epoch-seconds",
        example: "1709802900",
        note: "One panel partner fills the same column with milliseconds. A 13-digit value is the year 56000 to anything that assumes seconds, and it sorts last rather than erroring. Unit: seconds.",
      },
      {
        name: "horizontal_accuracy",
        type: "float",
        example: "12.5",
        min: 3,
        max: 120,
        nullable: true,
        note: "The radius of a 68% confidence circle, not an error bar. iOS reports -1 for an invalid fix and Android rows arrive with 0, and a filter that keeps rows under 50 m keeps both of those. Unit: metres.",
      },
      {
        name: "altitude",
        type: "float",
        example: "34.2",
        min: -20,
        max: 320,
        nullable: true,
        note: "Metres above the WGS84 ellipsoid on iOS and whatever the fused provider guessed on Android, which differ by tens of metres in the same street. A large share of rows are simply 0. Unit: metres.",
      },
      {
        name: "speed",
        type: "float",
        example: "3.4",
        min: 0,
        max: 33,
        nullable: true,
        note: "Metres per second from the SDK and km/h from one panel. A 0 means the platform did not fill it in far more often than it means the device stood still. Unit: metres per second.",
      },
      {
        name: "geo_type",
        type: "int",
        example: "1",
        min: 1,
        max: 3,
        note: "OpenRTB device.geo.type: 1 GPS, 2 IP address, 3 user-provided. The adapter sets it rather than measuring it, so a 1 is a claim about the fix and not evidence of one.",
      },
      {
        name: "geo_hash",
        type: "string",
        example: "gcpvj0d",
        nullable: true,
        note: "Geohash computed at ingest, before any privacy rounding, so it disagrees with the lat/lon beside it by a few hundred metres and stays well-formed while doing it.",
      },
      {
        name: "app_bundle",
        type: "string",
        values: ["com.weatherlive.forecast","com.puzzlequest.match3","com.newsdaily.reader","com.fitnesstrack.run","1234567890","com.localdeals.shop","com.radioplus.stream","com.flashlight.torch","com.busroute.times"],
        note: "OpenRTB says iOS should carry the numeric App Store id and Android the package name; half the exchanges send reverse-DNS for both. Joining to an app catalogue matches about two thirds of the rows.",
      },
      {
        name: "device_os",
        type: "string",
        values: ["iOS","Android","ios","android",""],
        nullable: true,
        note: "Casing depends on the adapter, so a GROUP BY returns four rows for two operating systems.",
      },
      {
        name: "publisher_id",
        type: "string",
        example: "pub-4471029",
        nullable: true,
        note: "Empty on SDK-sourced rows, which are the ones anybody actually trusts, so filtering to known publishers drops the best data in the file.",
      },
      {
        name: "iso_country_code",
        type: "string",
        values: ["GBR","GB","USA","US","DEU",""],
        nullable: true,
        note: "Alpha-3 from the exchange, alpha-2 from the SDK, empty when the fix came from an IP lookup. A country filter written for one form silently drops the other.",
      },
      {
        name: "source_type",
        type: "string",
        values: ["sdk","bidstream","exchange","panel"],
        note: "The only signal of how precise the coordinate really is, and it names the last hop rather than the origin of the fix.",
      },
    ],
    apt: ["precision-drift","dense-cluster","coincident","duplicates","date-chaos","null-empties"],
  },
  {
    id: "poi-venues",
    label: "Points of Interest (POI)",
    family: "adtech",
    blurb: "opening_hours is free text and the file switches category taxonomy halfway through, so an open-now filter and a category legend each work on the half you are not looking at.",
    geometry: "scatter",
    fields: [
      {
        name: "placekey",
        type: "string",
        example: "222-227@5vg-7gt-qzz",
        note: "The what@where form, where the @where half is an H3 cell. Every venue in one building shares it, so deduplicating on the suffix merges the whole block into one shop.",
      },
      {
        name: "parent_placekey",
        type: "string",
        example: "zzy-222@5vg-7gt-qzz",
        nullable: true,
        note: "The enclosing centre for a tenant and empty for a standalone site. Empty is read as 'no parent' when it usually means the conflation never found one.",
      },
      {
        name: "location_name",
        type: "string",
        values: ["Kings Cross Coffee Co","Northgate Pharmacy","The Old Mill Pub","Harbour Fish Bar","Central Dry Cleaners","Bridge Street Bakery","Green Park Newsagent","Quay Hardware","Market Row Barbers","Station Convenience"],
        note: "Carries the store number for some brands (#1042) and not for others, so matching a chain across two providers splits it in two.",
      },
      {
        name: "brands",
        type: "string",
        values: ["Starbucks,Teavana","Tesco","Costa Coffee","Boots","","Pret A Manger,Itsu"],
        nullable: true,
        note: "Empty for independents and comma-separated for co-branded sites — a multi-valued field inside a single cell, which is where an export written without a CSV writer comes apart.",
      },
      {
        name: "naics_code",
        type: "string",
        values: ["445110","722511","722513","722515","457110","447110","458110","812112","621210","713940"],
        nullable: true,
        note: "2022 NAICS renumbered petrol stations from 447110 to 457110 and both vintages sit in this column. It is a string in one extract and an int in the next, so a join has to guess.",
      },
      {
        name: "top_category",
        type: "string",
        values: ["Restaurants and Other Eating Places","Grocery Stores","Gasoline Stations","Clothing Stores","Personal Care Services","Other Amusement and Recreation Industries"],
        nullable: true,
        note: "Sometimes the NAICS title, sometimes an internal label like 'QSR - Drive Thru'. The same venue reads as two different categories depending on which extract you were sent.",
      },
      {
        name: "opening_hours",
        type: "string",
        example: "Mo-Fr 09:00-17:00; Sa 10:00-14:00",
        nullable: true,
        note: "Free text. OSM syntax, 12-hour ranges, a JSON day map as a quoted string and 'Call for hours' all live here, and none of them parse as the others.",
      },
      {
        name: "street_address",
        type: "string",
        values: ["12 Bridge St, Unit 4","148 Harbour Road","3A Market Row","Unit 7, Quay Retail Park","221 Station Approach","8 Green Park Lane"],
        note: "Contains a comma often enough that an export written by joining values shifts every column to its right on exactly the rows with unit numbers.",
      },
      {
        name: "postal_code",
        type: "string",
        values: ["07030","02139","01060","06902","03301","10001","33139","60614","94110","98101"],
        note: "A string only because of the leading zero, which the first spreadsheet to open the file removes and nothing downstream notices.",
      },
      {
        name: "phone_number",
        type: "string",
        example: "+44 20 7946 0000",
        nullable: true,
        note: "E.164 from one source, digits-only from another, (201) 555-0143 from the scrape. Matching venues on phone number matches none of them.",
      },
      {
        name: "polygon_class",
        type: "string",
        values: ["OWNED_POLYGON","SHARED_POLYGON"],
        nullable: true,
        note: "SHARED_POLYGON means the geometry is the parent centre's outline repeated on every tenant, not a footprint that belongs to this row. Null is not the same as OWNED and gets treated as it anyway.",
      },
      {
        name: "polygon_area_sq_ft",
        type: "float",
        example: "2450.0",
        min: 600,
        max: 12000,
        nullable: true,
        note: "Square feet in a file whose distances are metres, and on shared rows it is the whole centre's area rather than the unit's. Unit: square feet.",
      },
      {
        name: "is_permanently_closed",
        type: "string",
        values: ["false","FALSE","false","0","f","false","true","TRUE","1"],
        note: "true/false, TRUE/FALSE, 1/0 and t/f depending on the extract. A string comparison against 'true' leaves most of the closed shops on the map.",
      },
      {
        name: "tracking_closed_since",
        type: "iso-datetime",
        example: "2023-11-01",
        nullable: true,
        note: "Date-only values in a column typed as a timestamp, and the closed rows are still shipped in the current file rather than removed from it.",
      },
    ],
    apt: ["duplicates","mixed-geometry","null-empties","unicode-chaos","injection-strings","awkward-keys"],
  },
  {
    id: "geosocial-checkins",
    label: "Geosocial & Check-in",
    family: "adtech",
    blurb: "Posts without a GPS fix inherit the venue's point or the place's bounding box, so a heatmap is a few hundred infinitely dense pins plus one 30 km rectangle nobody ordered.",
    geometry: "scatter",
    fields: [
      {
        name: "post_id",
        type: "string",
        example: "1789234567890123456",
        note: "A 64-bit snowflake held as a string because a JSON number cannot carry it. Anything that parses it as a number changes the last three digits, which is why the API also returns an id_str.",
      },
      {
        name: "author_handle",
        type: "string",
        values: ["@northwharf","@cityrunner_92","@quaylife","@marketrowfan","@commuter_daily","@harbourlights"],
        note: "Handles are reusable after deletion, so the same handle is two different people across a year of collection. The stable numeric user id is the one field the collector did not keep.",
      },
      {
        name: "created_at",
        type: "iso-datetime",
        example: "2024-03-07T09:15:00Z",
        note: "ISO with a Z from the v2 API and 'Wed Mar 07 09:15:00 +0000 2024' from v1.1 archives, in the same column. The mobile SDK rows are local time with no offset at all.",
      },
      {
        name: "lang",
        type: "string",
        values: ["en","en-GB","en-gb","und","es","ja"],
        note: "Machine-detected, not declared. 'und' is the majority on emoji-only posts, which are also the ones sentiment scores worst.",
      },
      {
        name: "place_id",
        type: "string",
        example: "07d9db41a8b2c1e5",
        nullable: true,
        note: "Present exactly when the exact coordinate is absent, so it is a proxy for how wrong the position beside it is.",
      },
      {
        name: "place_full_name",
        type: "string",
        values: ["Camden, London","Shoreditch, London","Southwark, London","Hackney, London","London, United Kingdom"],
        nullable: true,
        note: "User-created on some networks, so 'home', 'work' and joke venues sit in this column next to real ones. The comma in it is the one that breaks the CSV.",
      },
      {
        name: "place_type",
        type: "string",
        values: ["poi","neighborhood","city","admin","country"],
        nullable: true,
        note: "The only thing separating a 10 m fix from a 30 km rectangle, and it is absent on the older rows entirely.",
      },
      {
        name: "body_text",
        type: "string",
        values: ["queue out the door ☕️🙃 #kingscross","third train cancelled this week","best flat white on the row, no notes","closed for refurb until the 14th??","sunset from the quay tonight 🌅","they've moved the entrance again"],
        note: "Emoji, newlines, right-to-left runs and unescaped quotes. It is the field that decides whether your popup escaping and CSV quoting actually work.",
      },
      {
        name: "hashtags",
        type: "string",
        values: ["kingscross;coffee;queue","london;commute","","food;london;review","sunset"],
        nullable: true,
        note: "A delimited list inside one cell, semicolons from one collector and commas from another, with no way to tell a delimiter from a tag containing one.",
      },
      {
        name: "like_count",
        type: "int",
        example: "14",
        min: 0,
        max: 250,
        note: "A snapshot at collection time, not at post time, so older posts look more popular purely for having been collected later.",
      },
      {
        name: "venue_checkin_count",
        type: "int",
        example: "48213",
        min: 200,
        max: 90000,
        nullable: true,
        note: "The venue's lifetime total repeated on every post at that venue. Summing the column multiplies it by the number of posts you happened to collect.",
      },
      {
        name: "sentiment_score",
        type: "float",
        example: "-0.42",
        min: -1,
        max: 1,
        nullable: true,
        note: "-1..1 from the current model and 0..100 from the one before it, in the same column. A 0 is either neutral or the most negative post in the file.",
      },
      {
        name: "sentiment_label",
        type: "string",
        values: ["positive","neutral","negative","POS","NEU","NEG"],
        nullable: true,
        note: "Written by a different model run than the score, so label and sign disagree on a few percent of rows and neither is marked as stale.",
      },
      {
        name: "is_retweet",
        type: "string",
        values: ["false","f","0","FALSE","false","true","t","1","TRUE"],
        note: "true/false from the API, t/f from a Postgres dump, 1/0 from the CSV. Filtering reposts out with one convention leaves the other two in.",
      },
    ],
    apt: ["coincident","dense-cluster","unicode-chaos","injection-strings","id-chaos","mixed-geometry"],
  },
  {
    id: "trade-area-catchment",
    label: "Trade Area & Catchment",
    family: "adtech",
    blurb: "One store ships as three nested drive-time rings, so a visitor choropleth counts the nearest households three times and the shares sum past 200%.",
    geometry: "zone",
    fields: [
      {
        name: "placekey",
        type: "string",
        example: "222-227@5vg-7gt-qzz",
        note: "The join key back to the POI file. It identifies the site, not the row, so it repeats once per band.",
      },
      {
        name: "store_id",
        type: "string",
        example: "GB-0417",
        note: "Repeated once per band, so despite the name it is not a key and a join on it fans the row count out by three or four.",
      },
      {
        name: "banner_name",
        type: "string",
        values: ["Northgate Express","Harbour Foods","City Pharmacy","Quay Market","Green Park Stores"],
        nullable: true,
        note: "The trading fascia rather than the legal entity, and it changes mid-panel when a chain rebrands, splitting one store's history in two.",
      },
      {
        name: "trade_area_type",
        type: "string",
        values: ["drivetime","drive_time","radius","custom"],
        note: "Both spellings arrive, from two versions of the same exporter, so a filter on one silently halves the file.",
      },
      {
        name: "drive_time_minutes",
        type: "string",
        values: ["5","10","15","20","30"],
        nullable: true,
        note: "A string in one extract and an int in the next, and null on radius and custom rows — which is exactly how the bands get flattened into one layer by anything that groups on it.",
      },
      {
        name: "radius_miles",
        type: "float",
        example: "3.5",
        min: 0.5,
        max: 12,
        nullable: true,
        note: "Miles in the name, kilometres in the values on every row from the EU panel. A 3.5 is either 5.6 km or 3.5 km and nothing in the row decides it. Unit: miles.",
      },
      {
        name: "visitor_home_cbg",
        type: "string",
        example: "360610127001",
        note: "A 12-digit block-group GEOID with a leading zero across the whole north-east, and 11-digit tract ids from the older vintage in the same column.",
      },
      {
        name: "raw_visit_counts",
        type: "int",
        example: "1840",
        min: 5,
        max: 9000,
        note: "Visits, not visitors: one person on four trips is a 4 here and a 1 in the column beside it. Averaging the two together is the usual way a footfall report doubles.",
      },
      {
        name: "raw_visitor_counts",
        type: "int",
        example: "620",
        min: 3,
        max: 4000,
        note: "Panel devices, not people, and small cells are withheld rather than reported — so this is sometimes larger than the visit count it is supposed to be a subset of.",
      },
      {
        name: "visitor_share_pct",
        type: "float",
        example: "38.4",
        min: 0.2,
        max: 42,
        note: "Computed within a band, so the three bands belonging to one store each sum to 100 and together sum to 300. Unit: percent.",
      },
      {
        name: "median_dwell",
        type: "float",
        example: "41.5",
        min: 4,
        max: 180,
        note: "Minutes here and seconds in the visits export it was derived from. A 41 is either a shop or a lunch, and the column name never said. Unit: minutes.",
      },
      {
        name: "distance_from_home",
        type: "float",
        example: "8420.0",
        min: 400,
        max: 40000,
        note: "Metres, in a file whose radii are miles. It is also a median across devices, so it cannot be summed or weighted-averaged with anything. Unit: metres.",
      },
      {
        name: "date_range_start",
        type: "iso-datetime",
        example: "2024-01-01",
        note: "Shipped with the store's local UTC offset rather than Z, so sorting these as strings interleaves timezones, and the ranges overlap between rows for the same store.",
      },
      {
        name: "date_range_end",
        type: "iso-datetime",
        example: "2024-03-31",
        note: "Inclusive on some vintages and exclusive on others, which shifts every quarterly total by a day's traffic in whichever direction nobody checked.",
      },
    ],
    apt: ["duplicates","wrong-winding","self-intersecting","holes","wrong-bbox","vertex-bomb"],
  },
  {
    id: "psychographics-spending",
    label: "Psychographics & Spending",
    family: "adtech",
    blurb: "Suppressed cells arrive as -666666666 rather than null, so the mean income is minus forty million and every real value lands in one bin of the colour ramp.",
    geometry: "zone",
    fields: [
      {
        name: "zcta5ce20",
        type: "string",
        values: ["07030","02139","01060","06902","03301","10001","33139","60614","94110","98101"],
        note: "The TIGER column name with the vintage baked into it. A 2010-keyed row in the same file is a different area under the same five digits.",
      },
      {
        name: "zip_code",
        type: "string",
        values: ["07030","02139","01060","06902","03301","10001","33139","60614","94110","98101"],
        nullable: true,
        note: "Duplicates zcta5ce20 on most rows and disagrees on the ones using a delivery ZIP that has no ZCTA polygon at all — there are several thousand more ZIPs than ZCTAs.",
      },
      {
        name: "segment_code",
        type: "string",
        values: ["A01","B05","D14","E17","G26","H31","K41","M52","O64"],
        note: "A group letter and a two-digit type. Some extracts drop the leading zero on single-digit types, so E07 and E7 are one segment shown twice in the legend.",
      },
      {
        name: "segment_name",
        type: "string",
        values: ["Aspiring Homemakers","Bank of Mum and Dad","Rural Vogue","Modest Traditions","Urban Cohesion","Family Basics"],
        nullable: true,
        note: "Renamed between vendor releases while the code stayed put, so the same code carries two names across a multi-year file.",
      },
      {
        name: "household_count",
        type: "int",
        example: "4127",
        min: 0,
        max: 12000,
        note: "0 means suppressed, not empty. Every per-household rate then divides by zero and the colour ramp collapses onto the infinities.",
      },
      {
        name: "median_hh_income",
        type: "int",
        example: "68420",
        min: 24000,
        max: 250001,
        nullable: true,
        note: "ACS B19013_001E carried through unchanged: 250001 is the top-code for '250,000 or more' rather than a real income, and the jam values are large negatives. Unit: USD.",
      },
      {
        name: "index_vs_national",
        type: "float",
        example: "132.4",
        min: 30,
        max: 190,
        note: "100 is average, not 100%. Put on the same equal-interval ramp as the percentage columns, an ordinary neighbourhood reads as extreme.",
      },
      {
        name: "avg_monthly_spend",
        type: "float",
        example: "412.75",
        min: 40,
        max: 900,
        nullable: true,
        note: "Dollars on most rows and cents on rows from the card panel, so a hundredfold difference looks like an affluent postcode. Unit: USD.",
      },
      {
        name: "spend_category",
        type: "string",
        values: ["grocery","Grocery","QSR","apparel","fuel","home_improvement","5411"],
        note: "Casing is inconsistent between suppliers and one of them ships the raw four-digit MCC instead, so a GROUP BY splits grocery three ways.",
      },
      {
        name: "penetration_pct",
        type: "float",
        example: "18.6",
        min: 0,
        max: 100,
        nullable: true,
        note: "0-100 from one vendor and 0-1 from the other, both named as a percentage. The 0-1 rows render as the palest colour in the ramp rather than as an error. Unit: percent.",
      },
      {
        name: "confidence_flag",
        type: "string",
        values: ["high","medium","low","suppressed"],
        nullable: true,
        note: "Null on the older vintage, which is not the same as high — but it is what a coalesce-to-default will make it.",
      },
      {
        name: "margin_of_error",
        type: "float",
        example: "6.2",
        min: 0.5,
        max: 24,
        nullable: true,
        note: "A 90% margin, not a standard error, and it is in the units of the estimate it describes — index points on the index columns and dollars on the income one.",
      },
      {
        name: "data_vintage",
        type: "string",
        values: ["2023 ACS 5-year","ACS 2019-2023","2018-2022 ACS","2020 Census","2023 ACS 5-Year"],
        nullable: true,
        note: "Free text naming a source rather than a date. 'ACS 2019-2023' and '2023 ACS 5-year' are one thing to a reader and two to a filter.",
      },
    ],
    apt: ["null-empties","unstable-types","mixed-schema","holes","duplicates","awkward-keys"],
  },
];
