import type { DataProfile } from "./index";

/**
 * Things that move, and the feeds that track them.
 *
 * Every one of these is a position report with a schema wrapped round it, and
 * every one of them encodes "I don't know" as a number in the same column as a
 * real measurement — 511 for no gyro, 102.3 for no speed, 0 for an altitude
 * that is really a stand. That is the family trait worth testing for.
 */
export const MOBILITY_PROFILES: DataProfile[] = [
  {
    id: "flight-adsb",
    label: "Flight & aviation (ADS-B)",
    family: "mobility",
    blurb: "Ground speed is metres per second and altitude is metres, so a 450 kt cruise reads 231 and slides past every sanity check written for knots.",
    geometry: "track",
    fields: [
      {
        name: "icao24",
        type: "string",
        example: "4ca7b5",
        note: "The 24-bit transponder address in hex, and the only stable identifier in the row. OpenSky lower-cases it while ADS-B Exchange and most receivers upper-case it, so a join between two feeds silently matches nothing.",
      },
      {
        name: "callsign",
        type: "string",
        example: "BAW117",
        nullable: true,
        note: "Eight characters on the wire, space-padded on the right. It is the flight number the crew typed in, not the registration, so the same airframe flies under a different one tomorrow, and it is blank while the transponder sits on standby.",
      },
      {
        name: "origin_country",
        type: "string",
        values: ["United Kingdom","Germany","Ireland","Netherlands","France","Spain","United States","Turkey","Norway","United Arab Emirates"],
        note: "Derived from the icao24 allocation block, not from where the aircraft is or where it is going. A UK-registered jet over Lagos still reads United Kingdom, and every dashboard that colours by it is drawing the registry.",
      },
      {
        name: "time_position",
        type: "epoch-seconds",
        example: "1709802900",
        nullable: true,
        note: "Seconds since the epoch for the last positional message. Null once that is older than the receiver's timeout, while the same row still carries an altitude and a velocity from the last message of any kind.",
      },
      {
        name: "last_contact",
        type: "epoch-seconds",
        example: "1709802907",
        note: "The last message of any kind, positional or not, so it runs ahead of time_position on a stale row. Sort on the wrong one of the two and stale rows interleave with live ones.",
      },
      {
        name: "baro_altitude",
        type: "float",
        example: "10972.8",
        min: -400,
        max: 14000,
        nullable: true,
        note: "Metres in the OpenSky API and feet in anything a dump1090 receiver wrote. 10972.8 and 36000 are the same aeroplane, and nothing in the row says which you have. Unit: m.",
      },
      {
        name: "geo_altitude",
        type: "float",
        example: "11041.4",
        min: -400,
        max: 14500,
        nullable: true,
        note: "GNSS altitude. It disagrees with baro_altitude by up to 300 m at cruise, because baro is referenced to 1013.25 hPa rather than the ground. A chart plotting whichever is non-null draws a sawtooth. Unit: m.",
      },
      {
        name: "on_ground",
        type: "bool",
        example: "false",
        note: "True for stand and taxi returns. The altitude beside it is 0, or null, or the string \"ground\", depending on which decoder wrote the file.",
      },
      {
        name: "velocity",
        type: "float",
        example: "231.35",
        min: 0,
        max: 340,
        note: "Ground speed in metres per second, not knots. A 450 kt cruise reads 231, which passes a knots-shaped range check without complaint. Unit: m/s.",
      },
      {
        name: "true_track",
        type: "float",
        example: "287.4",
        min: 0,
        max: 360,
        note: "Clockwise from true north, and it wraps: the mean of 359 and 1 is 180, so an averaged heading arrow points due south on an aircraft flying due north. Unit: deg.",
      },
      {
        name: "vertical_rate",
        type: "float",
        example: "-6.5",
        min: -30,
        max: 30,
        nullable: true,
        note: "Metres per second here and feet per minute on a receiver feed, a factor of 196 between two files that look identical. Negative is descending. Unit: m/s.",
      },
      {
        name: "squawk",
        type: "string",
        values: ["7000","2000","1000","4571","0021","6104","3452","7700","7600","7500"],
        nullable: true,
        note: "Four octal digits carried as text, so there is no 8 or 9 in it. Parsed as an integer, 0021 becomes 21 and the leading zero never comes back; 7500, 7600 and 7700 are the codes an alerting path is meant to notice.",
      },
      {
        name: "category",
        type: "string",
        values: ["0","2","3","4","6","8","9","14","17"],
        note: "Emitter category: 0 no information, 2-6 light through heavy, 8 rotorcraft, 9 glider, 14 UAV, 17 surface service vehicle. 0 is the commonest value, and 17 means some of the ground movement in the file is a pushback tug rather than an aircraft.",
      },
      {
        name: "position_source",
        type: "string",
        values: ["0","1","2","3"],
        note: "0 ADS-B, 1 ASTERIX, 2 MLAT, 3 FLARM. An MLAT position is triangulated from message arrival times and can be kilometres out, and nothing else in the row admits it.",
      },
    ],
    apt: ["zm-coords","antimeridian","sparse-global","duplicates","null-empties","precision-drift"],
  },
  {
    id: "maritime-ais",
    label: "Maritime & shipping (AIS)",
    family: "mobility",
    blurb: "Every \"not available\" code is in band — heading 511, speed 102.3, position 91/181 — so nothing downstream can tell a missing fix from a moving ship.",
    geometry: "scatter",
    fields: [
      {
        name: "mmsi",
        type: "int",
        example: "235098123",
        min: 201000000,
        max: 775999999,
        note: "Nine digits identifying the transponder, not the hull, and not unique: hired sets and factory defaults are shared between vessels. The first three digits are the flag, so sorting on it groups every UK vessel together, and a 99xxxxxxx in the same column is a navigation buoy rather than a ship.",
      },
      {
        name: "imo",
        type: "string",
        example: "9074729",
        nullable: true,
        note: "The hull's permanent number, seven digits with a check digit. Most of the fleet transmits 0, Class B transponders never send it at all, and half the feeds prefix it with IMO — so a join on it across two files matches almost nothing.",
      },
      {
        name: "vessel_name",
        type: "string",
        values: ["MAERSK ESSEX","EVER GIVEN","NORDIC ORION","STENA IMPERO","BALTIC BREEZE","CMA CGM MARCO","PACIFIC DAWN","OCEAN TRADER","ARKLOW SPIRIT","FRISIAN STAR","HOEGH TARGET","SEA CHALLENGER","ANNA MARIA","PORT LEADER@@@@@@"],
        note: "Twenty six-bit characters: upper case, digits and a little punctuation, with no lower case and no accents, so Ærø arrives as RO. The slot is padded out with @ to fill all twenty.",
      },
      {
        name: "call_sign",
        type: "string",
        example: "2FGH8",
        nullable: true,
        note: "Seven characters from the same six-bit set, padded to width, and routinely blank on inland and fishing vessels.",
      },
      {
        name: "ship_type",
        type: "int",
        example: "70",
        min: 0,
        max: 99,
        note: "70-79 cargo, 80-89 tanker, 60-69 passenger, 30 fishing. A code rather than a quantity, and 0 means nobody configured the set, which is most of the small craft.",
      },
      {
        name: "nav_status",
        type: "string",
        values: ["0","1","2","3","4","5","6","7","8","11","12","14","15"],
        note: "0 under way using engine, 1 at anchor, 5 moored, 15 undefined; 9, 10 and 13 are reserved and never appear. It is picked by hand from a bridge menu, so \"under way\" at a berth is the normal case rather than an error.",
      },
      {
        name: "sog",
        type: "float",
        example: "12.7",
        min: 0,
        max: 102.3,
        note: "Speed over ground in tenths of a knot. 102.2 means 102.2 knots or above and 102.3 means not available, and the sentinel plots as a 190 km/h container ship. Unit: kn.",
      },
      {
        name: "cog",
        type: "float",
        example: "84.2",
        min: 0,
        max: 360,
        note: "Course over ground, in tenths of a degree on the wire. 360.0 is the not-available code and sits in the same column as a genuine 359.9. Unit: deg.",
      },
      {
        name: "true_heading",
        type: "int",
        example: "511",
        min: 0,
        max: 511,
        note: "Where the bow points, from the gyro, in whole degrees. 511 means no gyro is fitted, and averaging it into a fleet statistic drags the answer north. Unit: deg.",
      },
      {
        name: "rot",
        type: "int",
        example: "-128",
        min: -128,
        max: 127,
        note: "Rate of turn, scaled: degrees per minute is (value / 4.733) squared with the sign kept. -128 means not available and 0 means not turning, and the raw number reads as degrees per minute to anyone who does not check.",
      },
      {
        name: "timestamp",
        type: "int",
        example: "42",
        min: 0,
        max: 63,
        note: "A field called timestamp that is not a timestamp: it is the second of the UTC minute the fix was taken. 60 means unavailable, 61 manual input, 62 dead reckoning, 63 positioning system inoperative — four sentinels inside a field that reads as seconds.",
      },
      {
        name: "draught",
        type: "float",
        example: "12.5",
        min: 0,
        max: 25.5,
        nullable: true,
        note: "Decimetres on the wire, metres out of most decoders, and keyed in by the crew. 0.0 and 25.5 both mean nobody updated it after the last port. Unit: m.",
      },
      {
        name: "destination",
        type: "string",
        values: ["ROTTERDAM","NLRTM","RTM","FOR ORDERS","HAMBURG","DEHAM","ANTWERPEN","GBFXT","SEE ORDERS","BREMERHAVEN"],
        nullable: true,
        note: "Free text, twenty characters, typed at the bridge. ROTTERDAM, NLRTM, RTM and FOR ORDERS are the same voyage in four feeds, and there is no code list to normalise against.",
      },
      {
        name: "eta",
        type: "string",
        values: ["05141600","06010800","00000000","05142460","07031200","09151845","11302300","00001200"],
        nullable: true,
        note: "Month, day, hour and minute with no year and no timezone. Hour 24 and minute 60 are the not-available codes, so 05142460 is a valid ETA meaning \"no idea\", and 00000000 is what most of the fleet sends.",
      },
    ],
    apt: ["null-island","out-of-range","coincident","duplicates","string-numbers","sparse-global"],
  },
  {
    id: "fleet-telematics",
    label: "Telematics & fleet",
    family: "mobility",
    blurb: "The box is the identity, not the vehicle: swap a faulty unit mid-week and one lorry becomes two in every report keyed on it.",
    geometry: "track",
    fields: [
      {
        name: "device_serial",
        type: "string",
        example: "G9-8841-A02",
        note: "Identifies the box, not the vehicle. Swap a faulty unit mid-week and one lorry becomes two in every report keyed on it, with no field anywhere saying the two are the same asset.",
      },
      {
        name: "vin",
        type: "string",
        example: "1HGCM82633A004352",
        nullable: true,
        note: "Seventeen characters read off the CAN bus, and \"UNKNOWN\" or a run of zeros when the box never got them. It identifies a vehicle and, in a small fleet, a driver, so the file is personal data the moment it leaves the yard.",
      },
      {
        name: "driver_id",
        type: "string",
        example: "D-00417",
        nullable: true,
        note: "Null on every unassigned trip, which is most of the weekend, and reissued within weeks of someone leaving. A year of history keyed on it belongs to two people.",
      },
      {
        name: "event_type",
        type: "string",
        values: ["ignition_on","ignition_off","heartbeat","harsh_brake","harsh_accel","idle_start","idle_end","fault","tow","power_lost"],
        note: "Heartbeats outnumber everything else ten to one, and a trip exists only as the ignition pair bracketing them — there is no trip id anywhere in the feed.",
      },
      {
        name: "gps_fix_time",
        type: "iso-datetime",
        example: "2024-03-07T09:15:03Z",
        note: "The device's clock, not the server's. A box that lost power stamps 2000-01-01 until it reacquires the constellation, and those rows sort to the top of everything.",
      },
      {
        name: "odometer_km",
        type: "float",
        example: "184203.4",
        min: 0,
        max: 4294967.295,
        note: "A counter that only goes up, running with the file, so distance is a difference between two rows rather than a value in one. A reset or a rollover turns that difference into nonsense and nothing in the row flags either. Unit: km.",
      },
      {
        name: "engine_hours",
        type: "float",
        example: "6412.7",
        min: 0,
        max: 99999.9,
        note: "Counts idling as well as driving, and resets on its own schedule independently of odometer_km. A vehicle can gain hours and no distance all afternoon, which is correct and looks like a fault. Unit: h.",
      },
      {
        name: "speed",
        type: "float",
        example: "97",
        min: 0,
        max: 160,
        note: "There is no unit column anywhere in the feed. North American installs report mph and European ones km/h into this same field, and the field is called speed in both. Unit: km/h or mph.",
      },
      {
        name: "rpm",
        type: "int",
        example: "1850",
        min: 0,
        max: 8032,
        note: "Engine speed at 0.125 rpm per bit. Not-available is transmitted as all bits set, which a decoder that ignores the error range turns into 8,031 rpm on a parked lorry. Unit: rpm.",
      },
      {
        name: "coolant_temp_c",
        type: "int",
        example: "88",
        min: -40,
        max: 210,
        note: "J1939 sends it as one byte with a -40 offset. A decoder that forgets to subtract puts every engine forty degrees hot, which still looks entirely plausible. Unit: degC.",
      },
      {
        name: "fuel_level_pct",
        type: "float",
        example: "62.5",
        min: 0,
        max: 100,
        nullable: true,
        note: "Percent of tank, and null on the electric vehicles in the same mixed fleet — not 0, which is what a dashboard shows and what a chart will happily plot. Unit: %.",
      },
      {
        name: "dtc_code",
        type: "string",
        values: ["P0301","P0420","P0171","U0100","P20EE","SPN 3251 FMI 0","SPN 639 FMI 2","SPN 100 FMI 1"],
        nullable: true,
        note: "The vans report OBD-II codes and the heavy trucks report an SPN and FMI pair, into the same column. One code per row too, so the other four the vehicle threw at the same moment are dropped without a word.",
      },
      {
        name: "ignition_state",
        type: "bool",
        example: "true",
        note: "False while the position still moves 10-20 m a fix. That is multipath off the depot shed rather than a journey, and nothing in the row distinguishes the two.",
      },
      {
        name: "hdop",
        type: "float",
        example: "1.4",
        min: 0.5,
        max: 99.99,
        note: "Horizontal dilution of precision: above 5 the fix is worthless. It arrives beside coordinates written to seven decimal places.",
      },
    ],
    apt: ["dense-cluster","duplicates","degenerate","date-chaos","precision-drift","unstable-types"],
  },
  {
    id: "transit-gtfs",
    label: "Transit feeds (GTFS)",
    family: "mobility",
    blurb: "An arrival_time of 25:40:00 is what the spec demands for a trip past midnight, and every date library in the stack returns Invalid Date.",
    geometry: "scatter",
    fields: [
      {
        name: "stop_id",
        type: "string",
        example: "1_2340",
        note: "Unique within one feed and nowhere else. Merge two agencies and ids collide; strip the agency prefix that was keeping them apart and they collide silently.",
      },
      {
        name: "stop_code",
        type: "string",
        example: "40234",
        nullable: true,
        note: "The number printed on the pole that riders text for departures. A different namespace from stop_id, and blank on stops nobody boards at.",
      },
      {
        name: "stop_name",
        type: "string",
        values: ["Elm St & 4th Ave","High St / Station Rd","Queen's Park","Union Station - Bay 12","Rue de l'Église","Market Sq (stand C)","4th Ave & Elm St","Depot Rd, opp. the works"],
        note: "Carries ampersands, slashes, commas and apostrophes straight into XML and CSV, and the same junction turns up twice with the two street names the other way round.",
      },
      {
        name: "parent_station",
        type: "string",
        values: ["STN_UNION","STN_CENTRAL","STN_HARBOUR","STN_MARKET","STN_KINGS",""],
        nullable: true,
        note: "Empty for a plain stop — which in CSV is an empty string, not null — and a station id for platforms, in the same column. The station carries coordinates of its own, so it plots on top of its own platforms.",
      },
      {
        name: "route_short_name",
        type: "string",
        example: "N1",
        nullable: true,
        note: "\"N1\", \"7\", \"A\", or blank on feeds that only fill route_long_name. Read as a number, route 07 and route 7 merge into one and route A becomes NaN.",
      },
      {
        name: "route_type",
        type: "string",
        values: ["0","1","2","3","4","5","6","7","11","12"],
        note: "3 bus, 0 tram, 2 rail, 4 ferry — and there is no 8, 9 or 10. An integer column that must never be averaged or interpolated.",
      },
      {
        name: "route_color",
        type: "string",
        example: "FF6600",
        nullable: true,
        note: "Six hex digits with no leading hash, per the spec, and blank means white rather than unset. Dropped into CSS as it stands, it is an invalid colour.",
      },
      {
        name: "route_text_color",
        type: "string",
        example: "FFFFFF",
        nullable: true,
        note: "The colour for text drawn on route_color, in the same format and set independently. Nothing checks the pair for contrast, so white on white ships regularly.",
      },
      {
        name: "trip_id",
        type: "string",
        values: ["AWE1-2024-03-07-4471", "AWE1-2024-03-07-4472", "BXR2-2024-03-07-1180", "BXR2-2024-03-08-1181", "NGT9-2024-03-07-0042"],
        note: "Regenerated on every publish by most schedulers, so yesterday's saved alert, tile cache or realtime match points at a trip that no longer exists.",
      },
      {
        name: "direction_id",
        type: "int",
        example: "0",
        min: 0,
        max: 1,
        note: "0 and 1 mean whatever each agency decided, per route. Inbound on one route is outbound on the next in the same file.",
      },
      {
        name: "stop_sequence",
        type: "int",
        example: "14",
        min: 1,
        max: 200,
        note: "Increases along the trip but is not consecutive: agencies number 10, 20, 30 to leave room for insertions. It is an order, not an index, and never a count.",
      },
      {
        name: "arrival_time",
        type: "string",
        values: ["06:12:00","07:15:00","08:47:30","12:05:00","17:33:00","21:40:00","23:51:00","24:35:00"],
        note: "HH:MM:SS counted from the start of the service day, so it keeps going past 24:00:00 for a trip that continues after midnight. It is an offset, not a time of day, and not parseable as one.",
      },
      {
        name: "shape_dist_traveled",
        type: "float",
        example: "12.4",
        min: 0,
        max: 100000,
        nullable: true,
        note: "Distance along the shape in whatever unit the producer chose; the spec asks only for consistency within a trip. Metres, miles, kilometres and plain stop counts all ship in real feeds. Unit: unspecified.",
      },
      {
        name: "wheelchair_boarding",
        type: "string",
        values: ["0","1","2"],
        note: "0 means \"no information\", not \"no\". Filter accessible stops on != 2 and every unknown stays in the results; a blank value inherits from the parent station instead of meaning anything itself.",
      },
    ],
    apt: ["duplicates","coincident","null-island","null-empties","string-numbers","id-chaos"],
  },
  {
    id: "micromobility-mds",
    label: "Micromobility (MDS)",
    family: "mobility",
    blurb: "battery_pct is a fraction in MDS and a percentage in the feeds behind it, so a scooter at 0.87 shows as 1% and a van is sent to collect it.",
    geometry: "scatter",
    fields: [
      {
        name: "device_id",
        type: "string",
        example: "4a2b7c30-3b12-4a0f-9f21-6f6f1c5b2c11",
        note: "A UUID for the physical vehicle, stable for its life, and the one field a city is usually forbidden from publishing — so the public extract has to be keyed on something less useful.",
      },
      {
        name: "vehicle_id",
        type: "string",
        example: "SCT-0412",
        note: "The number printed on the stem, which is what a rider or an inspector reads. Providers rotate it between trips for privacy, so counting distinct values counts trips rather than vehicles.",
      },
      {
        name: "vehicle_type",
        type: "string",
        values: ["bicycle","cargo_bicycle","scooter","scooter_standing","scooter_seated","moped","car","delivery_robot","other"],
        note: "MDS 2.0 split scooter into scooter_standing and scooter_seated, and GBFS kept scooter as a deprecated form factor, so identical hardware ships under both spellings in one export.",
      },
      {
        name: "propulsion_types",
        type: "string",
        values: ["electric","human","human,electric_assist","electric_assist","combustion"],
        note: "An array in the JSON and a comma-joined string in every CSV made from it. Splitting on the comma works until a producer uses a semicolon or a space.",
      },
      {
        name: "vehicle_state",
        type: "string",
        values: ["available","reserved","on_trip","elsewhere","non_operational","non_contactable","removed","missing","unknown"],
        note: "\"elsewhere\" means outside the city's jurisdiction and \"removed\" means in the back of a van. Both still carry a position, and neither belongs on a public map.",
      },
      {
        name: "event_types",
        type: "string",
        values: ["trip_end","trip_start","maintenance","rebalance_pick_up","comms_lost","trip_leave_jurisdiction","battery_low,maintenance","agency_drop_off"],
        note: "Plural for a reason: \"maintenance,removed\" arrives in one field. It is supposed to agree with vehicle_state and frequently does not, because the two are written by different systems.",
      },
      {
        name: "battery_pct",
        type: "float",
        example: "0.87",
        min: 0,
        max: 100,
        nullable: true,
        note: "A fraction from 0 to 1 under MDS and a percentage from 0 to 100 in the operator APIs behind it, with aggregators passing both through untouched. A value of 1 is either full or nearly flat.",
      },
      {
        name: "current_range_meters",
        type: "float",
        example: "14237.5",
        min: 0,
        max: 60000,
        nullable: true,
        note: "Metres, and an estimate off the battery curve rather than a measurement: it moves 4 km between two fixes thirty seconds apart without the vehicle going anywhere. Unit: m.",
      },
      {
        name: "station_id",
        type: "string",
        example: "stn_0042",
        nullable: true,
        note: "Null for dockless vehicles, which is most of them, and a dock id for the docked half of the same fleet. No column says which kind of fleet a row belongs to.",
      },
      {
        name: "is_disabled",
        type: "bool",
        example: "false",
        note: "0 and 1 in GBFS JSON, true and false after one trip through a converter, and both forms turn up in the same export.",
      },
      {
        name: "is_reserved",
        type: "bool",
        example: "false",
        note: "A reserved vehicle is still published with a position, so the public map keeps offering it for the fifteen minutes somebody is walking towards it.",
      },
      {
        name: "last_reported",
        type: "epoch-seconds",
        example: "1709802900",
        nullable: true,
        note: "GBFS specifies POSIX seconds. A good share of producers put a millisecond clock in it instead and nothing rejects the row.",
      },
      {
        name: "publication_time",
        type: "epoch-millis",
        example: "1709802903000",
        note: "MDS counts in milliseconds, sitting beside last_reported's seconds in the same record, with nothing in either name to signal that the scales differ.",
      },
      {
        name: "geography_type",
        type: "string",
        values: ["operating_area","no_ride","no_parking","slow_zone","preferred_parking","restricted_area"],
        nullable: true,
        note: "Set only on the polygon rows. Point rows leave it empty, so a file holding both is half blank down that column and a zone filter quietly drops every vehicle.",
      },
    ],
    apt: ["mixed-geometry","holes","wrong-winding","unclosed-rings","dense-cluster","id-chaos"],
  },
];
