import type { DataProfile } from "./index";

/**
 * Land, buildings and the pipes underneath them.
 *
 * These come out of municipal GIS and CAD, which means projected coordinates
 * handed over as if they were degrees, units that change at the county line,
 * and geometry that was drawn to be looked at rather than to be topologically
 * sound.
 */
export const REALESTATE_PROFILES: DataProfile[] = [
  {
    id: "cadastral-parcels",
    label: "Cadastral & Parcel",
    family: "realestate",
    blurb: "LOT_SIZE is acres in one town's export and square feet in the next, and the LOT_UNITS column that would say which is blank. A 0.31 and a 13,503 are the same lot.",
    geometry: "parcel",
    fields: [
      {
        name: "APN",
        type: "string",
        example: "007-0123-045-0000",
        note: "The join key to the tax roll, and every county punctuates its own. Strip the dashes to match one county's roll and the next county's stops matching.",
      },
      {
        name: "LOC_ID",
        type: "string",
        example: "F_741234_2895600",
        nullable: true,
        note: "The standard parcel id is the centroid in state-plane metres with an F_ in front. It is a coordinate wearing an id's clothes, so it changes the moment anyone edits the geometry.",
      },
      {
        name: "OWNER1",
        type: "string",
        values: ["SMITH JOHN A & MARY T   ","PATEL R & PATEL S       ","NORTHGATE HOLDINGS LLC  ","OBRIEN MICHAEL          ","CITY OF SPRINGFIELD     ","TRUSTEES OF QUAY TRUST  ","WONG L K                ","HARBOUR ESTATES LTD     "],
        note: "ALL CAPS and padded to the DBF field width. Readers disagree about trimming, so one owner becomes three rows in a group-by.",
      },
      {
        name: "OWN_ADDR",
        type: "string",
        values: ["PO BOX 41","12 BRIDGE ST","148 HARBOUR RD","SAME","UNKNOWN",""],
        nullable: true,
        note: "Empty string rather than null on municipal and tax-exempt parcels, so a null check passes and the column is still empty.",
      },
      {
        name: "USE_CODE",
        type: "string",
        values: ["101","104","111","130","300","325","400","440","903","906","1010","1040"],
        note: "State class code as text, three digits in the old scheme and four in the new, both present in one file. Read as an integer, 101 and 1010 stop joining to the legend and the exempt 900s get averaged into the taxable statistics.",
      },
      {
        name: "ZONING",
        type: "string",
        example: "R-1",
        nullable: true,
        note: "Copied off the zoning layer at some point in the past and never refreshed against it, so it disagrees with the zoning polygon over the same lot.",
      },
      {
        name: "LAND_VAL",
        type: "int",
        example: "185400",
        min: 8000,
        max: 940000,
        note: "0 means exempt on some rows and not-yet-assessed on others. Either way it drags every mean down. Unit: USD.",
      },
      {
        name: "BLDG_VAL",
        type: "int",
        example: "412700",
        min: 0,
        max: 1800000,
        nullable: true,
        note: "Null on vacant land, 0 on a demolished structure the roll has not caught up with, and both get counted as buildings worth nothing. Unit: USD.",
      },
      {
        name: "TOTAL_VAL",
        type: "int",
        example: "598100",
        min: 15000,
        max: 2600000,
        note: "Equals LAND_VAL + BLDG_VAL on most rows and not on the abated ones, because abatements are applied to the total only. The arithmetic check fails exactly on the parcels worth looking at. Unit: USD.",
      },
      {
        name: "LOT_SIZE",
        type: "float",
        example: "0.31",
        min: 0.04,
        max: 6.5,
        note: "Acres when LOT_UNITS is A and square feet when it is S, in the same column. Sum the column without reading the other one and the answer is off by 43,560 on some share of the rows. Unit: acres or square feet, per LOT_UNITS.",
      },
      {
        name: "LOT_UNITS",
        type: "string",
        values: ["A","S"],
        nullable: true,
        note: "The column that says which unit LOT_SIZE is in. It is blank on the rows that came in from another town's export, and nobody joins to it anyway.",
      },
      {
        name: "SHAPE_Area",
        type: "float",
        example: "13503.44",
        min: 1800,
        max: 90000,
        note: "Esri's cached area in the source projection's units, exactly ten characters so a shapefile keeps the name and loses the meaning. Reproject the geometry to degrees and the number travels with it, now describing nothing. Unit: square feet (source state plane).",
      },
      {
        name: "LS_DATE",
        type: "string",
        values: ["20190412", "20210903", "20170228", "20221115", "20240701", "00000000", "19981230"],
        nullable: true,
        note: "Last sale date as YYYYMMDD text on most rows, '0' where the parcel has never sold, and '4/12/2019' where somebody fixed a row in Excel. Sorted as text it still works; parsed as a date it does not.",
      },
      {
        name: "LS_PRICE",
        type: "int",
        example: "415000",
        min: 0,
        max: 980000,
        nullable: true,
        note: "1 and 100 are the nominal considerations on a family transfer and 0 is a non-arm's-length sale. Median sale price by town moves by six figures depending on whether anyone filtered them out. Unit: USD.",
      },
    ],
    apt: ["web-mercator","unclosed-rings","wrong-winding","self-intersecting","holes","duplicates","awkward-keys","null-empties"],
  },
  {
    id: "building-footprints",
    label: "Building Footprints",
    family: "realestate",
    blurb: "HEIGHTROOF is feet in the layer that published it and metres in the one merged into it. Extrude both and a 400 ft tower comes out 400 m tall.",
    geometry: "footprint",
    fields: [
      {
        name: "BIN",
        type: "int",
        example: "1012345",
        min: 1000000,
        max: 5999999,
        note: "Building identification number, seven digits with the borough in the first. Unique per building, and reissued to the replacement once the original is demolished.",
      },
      {
        name: "BBL",
        type: "string",
        example: "1000160001",
        note: "Borough-block-lot, the join key to the tax lot: one digit, five, then four. Ten digits with a leading borough, so every spreadsheet on the way turns it into 1.00016E+09.",
      },
      {
        name: "MPLUTO_BBL",
        type: "string",
        example: "1000160001",
        nullable: true,
        note: "The BBL as the tax-lot layer spells it, which is not always the BBL two columns to the left. Join on the wrong one and the building lands on a different lot.",
      },
      {
        name: "HEIGHTROOF",
        type: "float",
        example: "38.6",
        min: 12,
        max: 185,
        nullable: true,
        note: "Height from ground to roof in feet, because the source publishes feet. Merge in any other city's footprints and the same column holds metres, with nothing to mark the change. Unit: feet.",
      },
      {
        name: "GROUNDELEV",
        type: "int",
        example: "27",
        min: 0,
        max: 320,
        nullable: true,
        note: "Ground elevation, not roof elevation. Whether it should be added to HEIGHTROOF depends on which extrusion the viewer wants, and the file does not say. Unit: feet (NAVD88).",
      },
      {
        name: "NUM_FLOORS",
        type: "float",
        example: "2.5",
        min: 1,
        max: 16,
        nullable: true,
        note: "Half-storeys are real and so are the zeros, which mean unknown rather than a building with no floors. Multiply by a storey height to fill in a missing HEIGHTROOF and the zeros flatten whole blocks.",
      },
      {
        name: "CNSTRCT_YR",
        type: "int",
        example: "1928",
        min: 1885,
        max: 2026,
        nullable: true,
        note: "0 and 1000 both stand in for not recorded. A histogram by decade grows a spike at the year zero and the pre-war stock looks smaller than it is.",
      },
      {
        name: "FEAT_CODE",
        type: "string",
        values: ["1001","1002","1003","1004","2100","2110","5100","5110"],
        note: "Only 2100 is an actual building; the rest are skybridges, garages, canopies and tanks. Skip the filter and a good share of your 'buildings' are roofs over air.",
      },
      {
        name: "LSTSTATYPE",
        type: "string",
        values: ["Constructed","Alteration","Demolition","Marked For Construction","Initial Import"],
        nullable: true,
        note: "The 'Demolition' rows stay in the file. The building is gone; the polygon is not, and nothing else in the row says so.",
      },
      {
        name: "GEOMSOURCE",
        type: "string",
        values: ["Photogramm","Other (Manual)","LiDAR","Aerial Imagery"],
        nullable: true,
        note: "Photogrammetric outlines are roofs traced off oblique imagery, manual ones are ground outlines. Same layer, systematically offset from each other by the height of the building.",
      },
      {
        name: "DOITT_ID",
        type: "int",
        example: "742019",
        min: 1,
        max: 1400000,
        note: "The department's own row id, renumbered on every full rebuild, so last year's saved id points at a different building this year.",
      },
      {
        name: "GLOBALID",
        type: "string",
        example: "{D5C8B0F1-2A47-4C7D-9E2A-6F0B1D2C3E44}",
        nullable: true,
        note: "Esri's GlobalID, braces included. Half the tools that consume it strip the braces and half do not, so the same building has two stable ids.",
      },
      {
        name: "LSTMODDATE",
        type: "string",
        values: ["08/16/2017 12:00:00 AM", "11/02/2020 12:00:00 AM", "03/09/2014 12:00:00 AM", "12/31/2021 12:00:00 AM"],
        note: "Month-first with a 12-hour clock, where 12:00 AM is midnight. Parsed as day-first, 08/16 throws and 05/06 quietly does not.",
      },
      {
        name: "Shape__Area",
        type: "float",
        example: "2418.77",
        min: 420,
        max: 12000,
        note: "ArcGIS's cached area in the source projection: eleven characters, two underscores, and units that stop meaning anything the moment the file is reprojected. A shapefile cuts it to Shape__Are. Unit: square feet (source state plane).",
      },
    ],
    apt: ["unclosed-rings","self-intersecting","holes","wrong-winding","duplicates","zm-coords","precision-drift","awkward-keys"],
  },
  {
    id: "zoning-land-use",
    label: "Zoning & Land Use",
    family: "realestate",
    blurb: "A split lot carries two districts in one string, M1-2/R8A, and a style rule keyed on the code matches neither. The block renders grey.",
    geometry: "zone",
    fields: [
      {
        name: "ZONEDIST1",
        type: "string",
        example: "R6B",
        note: "The primary district. On a split lot it holds two districts joined by a slash and matches no legend entry at all.",
      },
      {
        name: "ZONEDIST2",
        type: "string",
        example: "M1-2",
        nullable: true,
        note: "The second district on a split lot, populated on roughly one polygon in forty. Ignore it and those polygons are half wrong; honour it and every renderer needs a second pass.",
      },
      {
        name: "OVERLAY1",
        type: "string",
        example: "C1-4",
        nullable: true,
        note: "A commercial overlay covering part of a residence district. The polygon underneath still says residential and both are true at once.",
      },
      {
        name: "SPDIST1",
        type: "string",
        example: "MX-8",
        nullable: true,
        note: "Special purpose district. It changes the rules entirely and is the easiest column in the file to drop as mostly-null.",
      },
      {
        name: "SPLITZONE",
        type: "string",
        values: ["N","N","N","N","N","N","N","Y"],
        note: "Y where the lot straddles a zoning line, which is the flag that would tell you ZONEDIST2 matters. It reads N on plenty of lots that are split anyway.",
      },
      {
        name: "LANDUSE",
        type: "string",
        values: ["01","02","03","04","05","06","07","08","09","10","11"],
        nullable: true,
        note: "Two-character codes with a leading zero, 01 one-and-two-family through 11 vacant land. Read as integers, 01 through 09 collapse to single digits and stop joining to the legend.",
      },
      {
        name: "BUILTFAR",
        type: "float",
        example: "1.42",
        min: 0,
        max: 18,
        note: "Floor area ratio as built. Subtracted from the permitted FAR to find development capacity, so a spurious zero reads as a vacant lot in the middle of a built block.",
      },
      {
        name: "RESIDFAR",
        type: "float",
        example: "0.5",
        min: 0,
        max: 12,
        note: "0.0 means residential is not permitted here, not that the value is missing. Averaging the column is meaningless and everyone does it.",
      },
      {
        name: "COMMFAR",
        type: "float",
        example: "2",
        min: 0,
        max: 15,
        note: "Same trap as RESIDFAR one column over: a hard 0 where commercial is barred. Filtering 'FAR > 0' silently drops every residential district in the file.",
      },
      {
        name: "MAX_HEIGHT",
        type: "float",
        example: "45",
        min: 25,
        max: 420,
        nullable: true,
        note: "Feet in most ordinances and storeys in a few, and the column name commits to neither. A 6 and a 65 are the same limit. Unit: feet or storeys.",
      },
      {
        name: "JURISDICTION",
        type: "string",
        values: ["City of Springfield","Springfield Township","Northgate Borough","Harbour County","Unincorporated"],
        note: "Free text, so 'City of Springfield', 'SPRINGFIELD' and 'Springfield, City of' are three jurisdictions in a group-by over a statewide merge.",
      },
      {
        name: "ORDINANCE_NUM",
        type: "string",
        example: "2019-114",
        nullable: true,
        note: "The amendment that created the district. Thirteen characters, so a shapefile cuts it to ORDINANCE_ and the next ordinance column becomes ORDINANC_1.",
      },
      {
        name: "EFFECTIVE_DATE",
        type: "iso-datetime",
        example: "2024-03-18T00:00:00Z",
        nullable: true,
        note: "Amendments span decades, and rows are published once adopted rather than once in force — so some dates are in the future and are not the answer to 'what is the zoning here today'.",
      },
      {
        name: "SHAPE_STArea__",
        type: "float",
        example: "1842660.5",
        min: 120000,
        max: 40000000,
        note: "What ArcGIS calls Shape.STArea() once it has been through an export: fourteen characters, two trailing underscores, units from the source projection, and SHAPE_STAr by the time a shapefile has it. Unit: square feet (source state plane).",
      },
    ],
    apt: ["holes","wrong-winding","self-intersecting","duplicates","null-empties","mixed-schema","vertex-bomb","web-mercator"],
  },
  {
    id: "indoor-bim",
    label: "Indoor Mapping (IMDF/BIM)",
    family: "realestate",
    blurb: "The floor label is 'G' on one row, '0' on the next and 'LG' on a third while ordinal disagrees with all three. A floor filter shows an empty building.",
    geometry: "footprint",
    fields: [
      {
        name: "feature_type",
        type: "string",
        values: ["unit","opening","level","fixture","amenity","anchor","kiosk","section"],
        note: "IMDF ships one file per feature type; the flattened layer keeps them all in one table, where every row has a different set of meaningful columns.",
      },
      {
        name: "level_id",
        type: "string",
        example: "a4d0e1f2-8c3b-4f5e-9a01-2b7c6d5e4f30",
        nullable: true,
        note: "What joins a unit to its level. CAD conversions mint fresh ids on every export, so yesterday's level_id matches nothing in today's file.",
      },
      {
        name: "ordinal",
        type: "int",
        example: "0",
        min: -3,
        max: 42,
        note: "The storey index, 0 for ground. The building's own drawings number the ground floor 1, and whoever ran the conversion picked one convention without recording which.",
      },
      {
        name: "short_name",
        type: "string",
        example: "G",
        note: "The floor label as printed in the lift: 'G', '0', '01', 'LG', 'M' for mezzanine, '13A' where there is no 13. Sorted as text, floor 10 comes before floor 2.",
      },
      {
        name: "category",
        type: "string",
        values: ["room","walkway","elevator","escalator","stairs","restroom","office","retail","nonpublic","parking","platform","lobby","opening"],
        note: "Drives both the styling and the routing graph, and mixes unit categories with opening categories in one column. The 'opening' rows are the only thing connecting two rooms, and they are the ones most often dropped as clutter.",
      },
      {
        name: "restriction",
        type: "string",
        values: ["employeesonly","restricted","temporarilyclosed"],
        nullable: true,
        note: "Null means public. A viewer that reads null as unknown and hides it loses the entire concourse.",
      },
      {
        name: "UNIT_ID",
        type: "string",
        example: "HQ.B2.L04.118",
        note: "The Esri Indoors id from the other half of the merge. It encodes the floor in the middle of the string, which is the only place the floor is reliable.",
      },
      {
        name: "name",
        type: "string",
        values: ["Gate 12","Room 204","Stair Core B","Plant Room 3","Lobby","Meeting Room 7","WC 2"],
        nullable: true,
        note: "IMDF ships names as a language-keyed object, not a string, and a conversion flattens it to whichever key it found first. Labels go missing in exactly the venues that needed two languages.",
      },
      {
        name: "display_point",
        type: "string",
        example: "-0.127600,51.507200",
        nullable: true,
        note: "The label anchor, and the only thing keeping a room's label inside the room. It is a nested GeoJSON Point in the real feed, so a shapefile drops it and a CSV stringifies it.",
      },
      {
        name: "accessibility",
        type: "string",
        values: ["[\"wheelchair\"]","[\"wheelchair\",\"braille\"]","[\"braille\"]","[\"hearing\"]","[\"tactilepaving\"]","[\"sign\"]"],
        nullable: true,
        note: "A JSON array of strings in the real feed, which reaches a shapefile as that literal text and a CSV as the same thing with an unescaped comma inside it.",
      },
      {
        name: "GlobalId",
        type: "string",
        example: "3Bx7Fp2Cn4uOQ_KrN$1p2S",
        nullable: true,
        note: "The IFC GUID from the model: 22 characters of IFC base64 including $ and _. Survives a DBF, breaks a URL.",
      },
      {
        name: "IfcEntityType",
        type: "string",
        values: ["IfcSpace","IfcSlab","IfcWall","IfcDoor","IfcStair","IfcFurniture","IfcBuildingStorey"],
        nullable: true,
        note: "What the element was in Revit before it became a polygon. Thirteen characters, so a shapefile calls it IfcEntityT.",
      },
      {
        name: "Elevation",
        type: "float",
        example: "14.4",
        min: -12,
        max: 96,
        note: "Storey height in the model's own datum, not above sea level, and the project base point is wherever the architect left it. Added to a terrain elevation it puts the fourth floor underground. Unit: metres above the project base point.",
      },
      {
        name: "Area",
        type: "float",
        example: "318.5",
        min: 45,
        max: 3200,
        note: "Revit's computed area in whatever the project template's units were, sitting immediately beside an Elevation in metres. Unit: square feet.",
      },
    ],
    apt: ["coincident","null-island","zm-coords","unicode-chaos","awkward-keys","dense-cluster","precision-drift"],
  },
  {
    id: "utility-networks",
    label: "Infrastructure & Utilities",
    family: "realestate",
    blurb: "Mains are drawn flat with the depth left in an invert column, so the gas main and the storm sewer four metres beneath it share a vertex.",
    geometry: "network",
    fields: [
      {
        name: "ASSETID",
        type: "string",
        example: "SS-MH-00412",
        note: "The field crew's id, on a prefix scheme that changed in 2013. Half the network is still on the old one and both halves are in the file.",
      },
      {
        name: "FACILITYID",
        type: "string",
        example: "412",
        nullable: true,
        note: "The GIS layer's own id, kept alongside the asset register's. Nothing keeps the two in step, and joins to the maintenance system use whichever the last consultant preferred.",
      },
      {
        name: "SUBTYPECD",
        type: "int",
        example: "3",
        min: 1,
        max: 12,
        note: "A coded-domain integer whose lookup table stays behind in the geodatabase. Export to GeoJSON and every asset is a bare number with no legend.",
      },
      {
        name: "MATERIAL",
        type: "string",
        values: ["DI","PVC","VCP","CI","AC","HDPE","RCP","CONC","UNK",""],
        nullable: true,
        note: "'UNK', '' and null all appear in this column and all three mean the same thing. Counting materials gives three answers for unknown.",
      },
      {
        name: "DIAMETER",
        type: "float",
        example: "12",
        min: 4,
        max: 72,
        nullable: true,
        note: "Inches on the water layer and millimetres on the sewer layer, merged into one asset register under one column name. A 12 and a 300 are the same pipe. Unit: inches.",
      },
      {
        name: "INSTALLDATE",
        type: "iso-datetime",
        example: "1974-06-01T00:00:00Z",
        nullable: true,
        note: "Mains go in over a century, so this column spans the 1890s to last year. 1899-12-30 turns up wherever the Access front end had an empty date box, making it the oldest asset in the city by a wide margin.",
      },
      {
        name: "LIFECYCLESTATUS",
        type: "int",
        example: "2",
        min: 1,
        max: 3,
        note: "1 proposed, 2 active, 3 abandoned. Fifteen characters, so a shapefile calls it LIFECYCLES, and the abandoned mains stay in the register and in the length totals.",
      },
      {
        name: "OWNEDBY",
        type: "int",
        example: "1",
        min: 1,
        max: 3,
        note: "1 public, 2 private, 3 other, -1 unknown. It is a number, so somebody sums it.",
      },
      {
        name: "UPSTREAM_INVERT",
        type: "float",
        example: "214.8",
        min: 82,
        max: 340,
        nullable: true,
        note: "The elevation of the pipe's bottom at the upstream end, and the only depth information anywhere in the file — nothing on the geometry carries it. Seventeen characters truncate to UPSTREAM_I. Unit: feet (NAVD88).",
      },
      {
        name: "DOWNSTREAM_INVERT",
        type: "float",
        example: "212.1",
        min: 82,
        max: 340,
        nullable: true,
        note: "Should sit below UPSTREAM_INVERT and on a stretch of any real network it does not, because the line was digitised against the flow. Truncates to DOWNSTREAM, which reads like a direction. Unit: feet (NAVD88).",
      },
      {
        name: "MEASUREDLENGTH",
        type: "float",
        example: "412.6",
        min: 20,
        max: 900,
        note: "Measured in the field, so it disagrees with the drawn length by a few per cent — and by a lot on the segments that were redigitised. Unit: feet.",
      },
      {
        name: "Shape_Length",
        type: "float",
        example: "408.35",
        min: 20,
        max: 900,
        note: "Esri's cached length in the source projection's units, never recomputed on export. Two length columns, neither of which matches the geometry once it is in degrees. Unit: feet (source state plane).",
      },
      {
        name: "LAMPTYPE",
        type: "string",
        values: ["HPS","MH","MV","LED","INC"],
        nullable: true,
        note: "Only meaningful on the streetlight rows. Null on every pipe, which a completeness check reports as 80% missing data.",
      },
      {
        name: "WATTAGE",
        type: "int",
        example: "70",
        min: 35,
        max: 400,
        nullable: true,
        note: "0 after a retrofit that deleted the lamp record and kept the pole. Sum the column for a load estimate and the retrofitted streets draw nothing. Unit: watts.",
      },
    ],
    apt: ["degenerate","coincident","duplicates","null-empties","unstable-types","date-chaos","id-chaos","web-mercator"],
  },
];
